In [1]:
# import tejapi 
# tejapi.ApiConfig.api_base="http://10.10.10.66"
# tejapi.ApiConfig.api_key = "3jUCETU2KiPwGJeyETYOQd1TCoDoxX"
# tejapi.ApiConfig.ignoretz = True
# import pandas as pd
# import numpy as np
# import datetime
import matplotlib.pyplot as plt
from All_functions import *

## 測試API

In [32]:
acc_info = tejapi.get('TWN/AINVFACC_INFO_C',
 paginate = True,
  chinese_column_name=False)
acc_info

     fin_type  ord acct_code        cdesc acct_type
None
0           F    1      BP11           現金         B
1           F    2      BP12         約當現金         B
2           F    3      BP21         應收帳款         B
3           F    4      BP22        長期應收款         B
4           F    5      BP31           存貨         B
...       ...  ...       ...          ...       ...
206         F  207      R316       每股稅後淨利         R
207         F  208      M316  每股稅後淨利-移動四季         R
208         F  209      M317  常續性EPS-移動四季         R
209         F  210      R834         每人營收         R
210         F  211      M834    每人營收-移動四季         R

[211 rows x 5 columns]

In [3]:
rand_series = np.random.random_integers(0, len(acc_info),10)

C:\Users\2022011702\AppData\Local\Temp\ipykernel_14892\3005942798.py:1: DeprecationWarning: This function is deprecated. Please call randint(0, 211 + 1) instead
  rand_series = np.random.random_integers(0, len(acc_info),10)

In [4]:
selected_columns = acc_info.loc[rand_series, '科目中文名稱'].tolist()
selected_columns

['金融負債流動',
 '資產總計',
 '利息支出率-移動四季',
 '其他營運流動負債',
 '現金流量比率',
 '固定資產減損',
 '流動資產合計',
 '存貨',
 '金融資產流動',
 '資本公積']

In [5]:
TransferInternalCode(selected_columns)

TypeError: TransferInternalCode() missing 1 required positional argument: 'groups'

In [ ]:
acc_info[acc_info['科目中文名稱'].isin(selected_columns+['cash'])]

     產業表板  科目排序   會計科目       科目中文名稱 科目所屬類別
None
47      F    48   DEBT        長短期借款      B
48      F    49   MCSH         可用資金      B
62      F    63   IP43       生物資產減損      I
71      F    72   IV22       定息投資損益      I
97      F    98  CISNI       淨利潤-CF      C
114     F   115   CV22      處分策略性投資      C
145     F   146   R104        常續ROE      R
159     F   160   R112        業外收支率      R
168     F   169   R410      固定資產成長率      R
207     F   208   M316  每股稅後淨利-移動四季      R

In [ ]:
acc_info.loc[rand_series, ['會計科目','科目中文名稱']]

        會計科目     科目中文名稱
None
151     R106      營業利益率
27      BV42  資金貸與(非流動)
123     CT11      匯率影響數
114     CV22    處分策略性投資
77      IV41       利息收入
49    QUICK2     嚴格速動資產
123     CT11      匯率影響數
98     CIP21   提列呆帳(迴轉)
136     XV11       併購相關
178     R509      借款依存度

In [ ]:
# acc_code = tejapi.get('TWN/AINVFACC_TYPE_C',
#  paginate = True,
#   chinese_column_name=True)
# acc_code

     產業表版 表次    中文名稱  表次順序
None
0       F  B   資產負債表     1
1       F  C   現金流量表     2
2       F  I     損益表     3
3       F  R      比率     4
4       F  X  非經常性損益     5
5       F  Z    比率計算     6

In [ ]:

announce_date = tejapi.get('TWN/AINVFINQA',
 coid = ['2330','2303','2454'],
 paginate = True,
  chinese_column_name=True,
  opts = {})
announce_date

       公司碼         年月  次數 合併        發布日     會計開始月分     會計結束月分  期間   幣別
None
0     2303 2005-03-01   1  N 2006-04-29 2005-01-01 2005-03-31   3  NTD
1     2303 2005-06-01   1  Y 2006-08-31 2005-04-01 2005-06-30   6  NTD
2     2303 2005-09-01   1  N 2006-10-31 2005-07-01 2005-09-30   9  NTD
3     2303 2005-12-01   1  Y 2007-04-30 2005-10-01 2005-12-31  12  NTD
4     2303 2006-03-01   1  N 2006-04-29 2006-01-01 2006-03-31   3  NTD
...    ...        ...  .. ..        ...        ...        ...  ..  ...
300   2454 2021-09-01   2  Y 2022-11-11 2021-07-01 2021-09-30   9  NTD
301   2454 2021-12-01   1  Y 2022-02-25 2021-10-01 2021-12-31  12  NTD
302   2454 2022-03-01   1  Y 2022-05-13 2022-01-01 2022-03-31   3  NTD
303   2454 2022-06-01   1  Y 2022-08-12 2022-04-01 2022-06-30   6  NTD
304   2454 2022-09-01   1  Y 2022-11-11 2022-07-01 2022-09-30   9  NTD

[305 rows x 9 columns]

In [ ]:
# 將相同['公司碼','年月','發布日','合併']的資料，針對'次數'進行排序，再取次數較大的資料
x = announce_date.sort_values(['公司碼','年月','發布日','合併','次數']).groupby(['公司碼','年月','發布日','合併']).tail(1)
x

       公司碼         年月  次數 合併        發布日     會計開始月分     會計結束月分  期間   幣別
None
0     2330 2005-03-01   1  N 2006-05-02 2005-01-01 2005-03-31   3  NTD
1     2330 2005-06-01   1  Y 2006-07-28 2005-04-01 2005-06-30   6  NTD
2     2330 2005-09-01   1  N 2006-10-30 2005-07-01 2005-09-30   9  NTD
3     2330 2005-12-01   1  Y 2007-02-26 2005-10-01 2005-12-31  12  NTD
4     2330 2006-03-01   1  N 2006-05-02 2006-01-01 2006-03-31   3  NTD
...    ...        ...  .. ..        ...        ...        ...  ..  ...
98    2330 2021-09-01   2  Y 2022-11-14 2021-07-01 2021-09-30   9  NTD
99    2330 2021-12-01   1  Y 2022-02-25 2021-10-01 2021-12-31  12  NTD
100   2330 2022-03-01   1  Y 2022-05-13 2022-01-01 2022-03-31   3  NTD
101   2330 2022-06-01   1  Y 2022-08-12 2022-04-01 2022-06-30   6  NTD
102   2330 2022-09-01   1  Y 2022-11-14 2022-07-01 2022-09-30   9  NTD

[99 rows x 9 columns]

In [ ]:
# 檢查邏輯
x[(x['公司碼']=='2330')&(x['年月']=='2014-06-01')&(x['發布日']=='2014-08-13')&(x['合併']=='Y')].sort_values('次數',ascending = True).tail(1)

       公司碼         年月  次數 合併        發布日     會計開始月分     會計結束月分  期間   幣別
None
37    2330 2014-06-01   2  Y 2014-08-13 2014-04-01 2014-06-30   6  NTD

In [ ]:
unique_date = x.drop_duplicates()
# 針對相同['公司碼','發布日','合併']的資料，若遇到相同發布日的情況，選財報年月最大者
unique_date = unique_date.groupby(['公司碼','發布日','合併']).tail(1).reset_index(drop=True)
unique_date = unique_date.sort_values(['公司碼','年月','發布日','合併','次數'])
# unique_date

      公司碼         年月  次數 合併        發布日     會計開始月分     會計結束月分  期間   幣別
8    2303 2007-03-01   1  N 2007-04-30 2007-01-01 2007-03-31   3  NTD
11   2303 2007-12-01   1  Y 2008-04-24 2007-10-01 2007-12-31  12  NTD
12   2303 2008-03-01   1  Y 2008-05-14 2008-01-01 2008-03-31   3  NTD
13   2303 2008-06-01   1  Y 2008-08-28 2008-04-01 2008-06-30   6  NTD
15   2303 2008-12-01   1  Y 2009-03-31 2008-10-01 2008-12-31  12  NTD
..    ...        ...  .. ..        ...        ...        ...  ..  ...
295  2454 2021-09-01   1  Y 2021-11-12 2021-07-01 2021-09-30   9  NTD
297  2454 2021-12-01   1  Y 2022-02-25 2021-10-01 2021-12-31  12  NTD
298  2454 2022-03-01   1  Y 2022-05-13 2022-01-01 2022-03-31   3  NTD
299  2454 2022-06-01   1  Y 2022-08-12 2022-04-01 2022-06-30   6  NTD
300  2454 2022-09-01   1  Y 2022-11-11 2022-07-01 2022-09-30   9  NTD

[157 rows x 9 columns]

In [ ]:
# unique_date = pd.DataFrame()
# for i in range(len(announce_date)):
#     temp = announce_date[(announce_date['公司碼']==announce_date.loc[i,'公司碼'])&(announce_date['年月']==announce_date.loc[i,'年月'])&(announce_date['發布日']==announce_date.loc[i,'發布日'])&(announce_date['合併']==announce_date.loc[i,'合併'])].sort_values('次數',ascending = True).tail(1)
#     unique_date = pd.concat([unique_date, temp])
# unique_date = unique_date.drop_duplicates().reset_index(drop=True)
# res = pd.DataFrame()
# for date in unique_date['發布日'].unique():
#     temp = unique_date[unique_date['發布日']==date].sort_values('年月', ascending=True).tail(1)
#     res = pd.concat([res, temp])
# res = res.sort_values(['公司碼','年月','發布日','合併','次數'])

In [ ]:
diff_index = (res.values == xx.values).all(axis = 1)
res[~diff_index], xx[~diff_index]

(Empty DataFrame
 Columns: [公司碼, 年月, 次數, 合併, 發布日, 會計開始月分, 會計結束月分, 期間, 幣別]
 Index: [],
 Empty DataFrame
 Columns: [公司碼, 年月, 次數, 合併, 發布日, 會計開始月分, 會計結束月分, 期間, 幣別]
 Index: [])

In [ ]:
announce_date[announce_date['年月']=='2021-03-01'], x[x['年月']=='2021-03-01'], xx[xx['年月']=='2021-03-01']

(       公司碼         年月  次數 合併        發布日     會計開始月分     會計結束月分  期間   幣別
 None
 93    2330 2021-03-01   1  Y 2021-05-14 2021-01-01 2021-03-31   3  NTD
 94    2330 2021-03-01   2  Y 2022-05-13 2021-01-01 2021-03-31   3  NTD,
        公司碼         年月  次數 合併        發布日     會計開始月分     會計結束月分  期間   幣別
 None
 93    2330 2021-03-01   1  Y 2021-05-14 2021-01-01 2021-03-31   3  NTD
 94    2330 2021-03-01   2  Y 2022-05-13 2021-01-01 2021-03-31   3  NTD,
      公司碼         年月  次數 合併        發布日     會計開始月分     會計結束月分  期間   幣別
 54  2330 2021-03-01   1  Y 2021-05-14 2021-01-01 2021-03-31   3  NTD)

In [ ]:
announce_date[announce_date['年月']=='2021-03-01'], unique_date[unique_date['年月']=='2021-03-01'], res[res['年月']=='2021-03-01'], res[res['發布日']=='2022-05-13']

(       公司碼         年月  次數 合併        發布日     會計開始月分     會計結束月分  期間   幣別
 None
 93    2330 2021-03-01   1  Y 2021-05-14 2021-01-01 2021-03-31   3  NTD
 94    2330 2021-03-01   2  Y 2022-05-13 2021-01-01 2021-03-31   3  NTD,
      公司碼         年月  次數 合併        發布日     會計開始月分     會計結束月分  期間   幣別
 89  2330 2021-03-01   1  Y 2021-05-14 2021-01-01 2021-03-31   3  NTD
 90  2330 2021-03-01   2  Y 2022-05-13 2021-01-01 2021-03-31   3  NTD,
      公司碼         年月  次數 合併        發布日     會計開始月分     會計結束月分  期間   幣別
 89  2330 2021-03-01   1  Y 2021-05-14 2021-01-01 2021-03-31   3  NTD,
      公司碼         年月  次數 合併        發布日     會計開始月分     會計結束月分  期間   幣別
 96  2330 2022-03-01   1  Y 2022-05-13 2022-01-01 2022-03-31   3  NTD)

In [ ]:
fin_data = tejapi.get('TWN/AINVFINQ',
 coid = '2330',
 paginate = True,
  chinese_column_name=True,
   opts= {'pivot':True})
fin_data

,公司碼,年月,次數,現金,約當現金,應收帳款,長期應收款,存貨,應付帳款,固定資產,...,每股營業收入-移動四季,每股營業利益,每股營業利益-移動四季,每股稅前淨益,每股稅前淨益-移動四季,每股稅後淨利,每股稅後淨利-移動四季,常續性EPS-移動四季,每人營收,每人營收-移動四季
None,,,,,,,,,,,,,,,,,,,,,
0,2330,2005-03-01,1,6.021899e+07,0.0,22428991.0,0.0,13428985.0,8207745.0,2.298537e+08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2984.40675,NaN
1,2330,2005-06-01,1,8.840515e+07,0.0,32095014.0,0.0,15158776.0,7605043.0,2.570064e+08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2914.70216,NaN
2,2330,2005-09-01,1,5.846733e+07,0.0,37248082.0,0.0,15070064.0,10042040.0,2.189094e+08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3419.32318,NaN
3,2330,2005-12-01,1,9.648371e+07,0.0,38477534.0,0.0,17728303.0,11164521.0,2.448233e+08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3787.60916,NaN
4,2330,2006-03-01,1,1.099898e+08,0.0,35779889.0,0.0,16901113.0,10873768.0,2.125225e+08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3859.45693,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98,2330,2021-09-01,2,8.538120e+08,0.0,187168224.0,0.0,182233752.0,43888861.0,1.861856e+09,...,58.26211,6.59472,24.07713,6.70455,24.65889,6.03459,22.11785,22.09659,7296.55257,26583.35746
99,2330,2021-12-01,1,1.064990e+09,0.0,198301433.0,0.0,193102321.0,48722789.0,2.007853e+09,...,61.21835,7.04856,25.06638,7.12752,25.57334,6.41616,23.02601,23.29538,6725.64627,24364.79367
100,2330,2022-03-01,1,1.151590e+09,0.0,213427901.0,0.0,200118682.0,50104079.0,2.137253e+09,...,66.17677,8.62996,27.88984,8.74725,28.33951,7.82335,25.45942,25.62231,7537.38754,26339.64698
101,2330,2022-06-01,1,1.253189e+09,0.0,222069236.0,0.0,217438091.0,59818066.0,2.282612e+09,...,72.42764,10.10875,32.38245,10.25817,32.83796,9.14681,29.42133,29.89569,8198.37930,28826.07389
102,2330,2022-09-01,1,1.296013e+09,0.0,261538308.0,0.0,218335874.0,62018224.0,2.453840e+09,...,80.08169,11.96759,37.75533,12.21312,38.34653,10.83549,34.22223,34.41798,9410.95811,31872.37122

In [ ]:
fin_ann_date = fin_data.merge(unique_date, left_on=['公司碼', '年月', '次數'], right_on= ['公司碼', '年月', '次數'], how='left')
fin_ann_date

,公司碼,年月,次數,現金,約當現金,應收帳款,長期應收款,存貨,應付帳款,固定資產,...,每股稅後淨利-移動四季,常續性EPS-移動四季,每人營收,每人營收-移動四季,合併,發布日,會計開始月分,會計結束月分,期間,幣別
0,2330,2005-03-01,1,6.021899e+07,0.0,22428991.0,0.0,13428985.0,8207745.0,2.298537e+08,...,NaN,NaN,2984.40675,NaN,NaN,NaT,NaT,NaT,NaN,NaN
1,2330,2005-06-01,1,8.840515e+07,0.0,32095014.0,0.0,15158776.0,7605043.0,2.570064e+08,...,NaN,NaN,2914.70216,NaN,NaN,NaT,NaT,NaT,NaN,NaN
2,2330,2005-09-01,1,5.846733e+07,0.0,37248082.0,0.0,15070064.0,10042040.0,2.189094e+08,...,NaN,NaN,3419.32318,NaN,N,2006-10-30,2005-07-01,2005-09-30,9.0,NTD
3,2330,2005-12-01,1,9.648371e+07,0.0,38477534.0,0.0,17728303.0,11164521.0,2.448233e+08,...,NaN,NaN,3787.60916,NaN,Y,2007-02-26,2005-10-01,2005-12-31,12.0,NTD
4,2330,2006-03-01,1,1.099898e+08,0.0,35779889.0,0.0,16901113.0,10873768.0,2.125225e+08,...,NaN,NaN,3859.45693,NaN,N,2006-05-02,2006-01-01,2006-03-31,3.0,NTD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98,2330,2021-09-01,2,8.538120e+08,0.0,187168224.0,0.0,182233752.0,43888861.0,1.861856e+09,...,22.11785,22.09659,7296.55257,26583.35746,NaN,NaT,NaT,NaT,NaN,NaN
99,2330,2021-12-01,1,1.064990e+09,0.0,198301433.0,0.0,193102321.0,48722789.0,2.007853e+09,...,23.02601,23.29538,6725.64627,24364.79367,Y,2022-02-25,2021-10-01,2021-12-31,12.0,NTD
100,2330,2022-03-01,1,1.151590e+09,0.0,213427901.0,0.0,200118682.0,50104079.0,2.137253e+09,...,25.45942,25.62231,7537.38754,26339.64698,Y,2022-05-13,2022-01-01,2022-03-31,3.0,NTD
101,2330,2022-06-01,1,1.253189e+09,0.0,222069236.0,0.0,217438091.0,59818066.0,2.282612e+09,...,29.42133,29.89569,8198.37930,28826.07389,Y,2022-08-12,2022-04-01,2022-06-30,6.0,NTD
102,2330,2022-09-01,1,1.296013e+09,0.0,261538308.0,0.0,218335874.0,62018224.0,2.453840e+09,...,34.22223,34.41798,9410.95811,31872.37122,Y,2022-11-14,2022-07-01,2022-09-30,9.0,NTD

In [ ]:
fin_ann_date[fin_ann_date['年月'] =='2014-06-01']

,公司碼,年月,次數,現金,約當現金,應收帳款,長期應收款,存貨,應付帳款,固定資產,...,每股稅後淨利-移動四季,常續性EPS-移動四季,每人營收,每人營收-移動四季,合併,發布日,會計開始月分,會計結束月分,期間,幣別
36,2330,2014-06-01,1,255053573.0,0.0,86887160.0,652000.0,50954265.0,21697296.0,837167426.0,...,NaN,NaN,4489.86787,15691.15465,NaN,NaT,NaT,NaT,NaN,NaN
37,2330,2014-06-01,2,255053573.0,0.0,86887160.0,652000.0,50954265.0,21697296.0,837167426.0,...,NaN,NaN,4489.86787,15691.15465,Y,2014-08-13,2014-04-01,2014-06-30,6.0,NTD
38,2330,2014-06-01,3,255053573.0,0.0,86887160.0,652000.0,50954265.0,21697296.0,837167426.0,...,NaN,NaN,4489.86787,15691.15465,NaN,NaT,NaT,NaT,NaN,NaN

In [ ]:
# fin_ann_date = fin_ann_date[~fin_ann_date['發布日'].isna()]
# fin_ann_date

,公司碼,年月,次數,現金,約當現金,應收帳款,長期應收款,存貨,應付帳款,固定資產,...,每股稅後淨利-移動四季,常續性EPS-移動四季,每人營收,每人營收-移動四季,合併,發布日,會計開始月分,會計結束月分,期間,幣別
2,2330,2005-09-01,1,5.846733e+07,0.0,37248082.0,0.0,15070064.0,10042040.0,2.189094e+08,...,NaN,NaN,3419.32318,NaN,N,2006-10-30,2005-07-01,2005-09-30,9.0,NTD
3,2330,2005-12-01,1,9.648371e+07,0.0,38477534.0,0.0,17728303.0,11164521.0,2.448233e+08,...,NaN,NaN,3787.60916,NaN,Y,2007-02-26,2005-10-01,2005-12-31,12.0,NTD
4,2330,2006-03-01,1,1.099898e+08,0.0,35779889.0,0.0,16901113.0,10873768.0,2.125225e+08,...,NaN,NaN,3859.45693,NaN,N,2006-05-02,2006-01-01,2006-03-31,3.0,NTD
5,2330,2006-06-01,1,1.414517e+08,0.0,37968877.0,0.0,20051180.0,10281660.0,2.511299e+08,...,NaN,NaN,3587.69380,NaN,Y,2006-07-28,2006-04-01,2006-06-30,6.0,NTD
6,2330,2006-09-01,1,9.290327e+07,0.0,37725640.0,0.0,20337674.0,10586959.0,2.606656e+08,...,NaN,NaN,3580.14433,14133.00195,Y,2007-10-30,2006-07-01,2006-09-30,9.0,NTD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,2330,2021-09-01,1,8.538120e+08,0.0,187168224.0,0.0,182233752.0,43888861.0,1.861856e+09,...,22.11785,22.09659,7296.55257,26583.35746,Y,2021-11-12,2021-07-01,2021-09-30,9.0,NTD
99,2330,2021-12-01,1,1.064990e+09,0.0,198301433.0,0.0,193102321.0,48722789.0,2.007853e+09,...,23.02601,23.29538,6725.64627,24364.79367,Y,2022-02-25,2021-10-01,2021-12-31,12.0,NTD
100,2330,2022-03-01,1,1.151590e+09,0.0,213427901.0,0.0,200118682.0,50104079.0,2.137253e+09,...,25.45942,25.62231,7537.38754,26339.64698,Y,2022-05-13,2022-01-01,2022-03-31,3.0,NTD
101,2330,2022-06-01,1,1.253189e+09,0.0,222069236.0,0.0,217438091.0,59818066.0,2.282612e+09,...,29.42133,29.89569,8198.37930,28826.07389,Y,2022-08-12,2022-04-01,2022-06-30,6.0,NTD
102,2330,2022-09-01,1,1.296013e+09,0.0,261538308.0,0.0,218335874.0,62018224.0,2.453840e+09,...,34.22223,34.41798,9410.95811,31872.37122,Y,2022-11-14,2022-07-01,2022-09-30,9.0,NTD

In [ ]:
# # trading table columns 
# trading_info = tejapi.get('TWN/ANPRCSTD',
#  paginate = True,
#   chinese_column_name=True)
# trading_info

In [ ]:
# stock price 
stk_price = tejapi.get('TWN/APRCD1',
 coid = '2330',
 paginate = True,
  chinese_column_name=True)

stk_price

,證券代碼,年月日,開盤價(元),最高價(元),最低價(元),收盤價(元),成交量(千股),成交值(千元),報酬率％,週轉率％,...,現金股利率,股價漲跌(元),高低價差%,次日開盤參考價,次日漲停價,次日跌停價,注意股票(A),處置股票(D),全額交割(Y),市場別
None,,,,,,,,,,,,,,,,,,,,,
0,2330,1994-09-05,1.7203,1.7203,1.7203,1.7203,4.000,3.840000e+02,6.6667,0.0005,...,NaN,NaN,NaN,96.0,102.5,89.5,,,,TSE
1,2330,1994-09-06,1.8368,1.8368,1.8368,1.8368,1.000,1.020000e+02,6.7708,0.0001,...,NaN,6.5,0.0000,102.5,109.5,95.5,,,,TSE
2,2330,1994-09-07,1.9623,1.9623,1.9623,1.9623,1.000,1.090000e+02,6.8293,0.0001,...,NaN,7.0,0.0000,109.5,117.0,102.0,,,,TSE
3,2330,1994-09-08,2.0967,2.0967,2.0967,2.0967,2.000,2.340000e+02,6.8493,0.0003,...,NaN,7.5,0.0000,117.0,125.0,109.0,,,,TSE
4,2330,1994-09-09,2.2400,2.2400,2.2400,2.2400,1.000,1.250000e+02,6.8376,0.0001,...,NaN,8.0,0.0000,125.0,133.5,116.5,,,,TSE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7204,2330,2023-01-17,504.0000,504.0000,499.5000,503.0000,29443.522,1.478466e+07,-0.3960,0.1135,...,2.1869,-2.0,0.8911,503.0,553.0,453.0,,,,TSE
7205,2330,2023-01-30,542.0000,543.0000,534.0000,543.0000,148413.161,8.005716e+07,7.9523,0.5724,...,2.0258,40.0,1.7893,543.0,597.0,489.0,,,,TSE
7206,2330,2023-01-31,537.0000,538.0000,521.0000,522.0000,79212.272,4.173694e+07,-3.8674,0.3055,...,2.1073,-21.0,3.1308,522.0,574.0,470.0,,,,TSE
7207,2330,2023-02-01,532.0000,533.0000,522.0000,530.0000,42539.626,2.245095e+07,1.5326,0.1641,...,2.0755,8.0,2.1073,530.0,583.0,477.0,,,,TSE
7208,2330,2023-02-02,538.0000,542.0000,537.0000,540.0000,46523.592,2.509148e+07,1.8868,0.1794,...,2.0370,10.0,0.9434,540.0,594.0,486.0,,,,TSE

In [ ]:
fin_ann_date.columns[fin_ann_date.columns.str.contains('移動四季')]

Index(['常續ROE-移動四季', '常續ROA-移動四季', '營業毛利率-移動四季', '營業利益率-移動四季', '稅前淨利率-移動四季',
       '稅後淨利率-移動四季', '營業費用率-移動四季', '業外收支率-移動四季', '現金流量比率-移動四季', '利息支出率-移動四季',
       '利息保障倍數-移動四季', '應收帳款週轉率-移動四季', '應付帳款週轉率-移動四季', '存貨週轉率-移動四季',
       '總資產週轉率-移動四季', '淨值週轉率-移動四季', '固定資產週轉率-移動四季', '期末收帳天數-移動四季',
       '期末付帳天數-移動四季', '期末售貨天數-移動四季', '淨營業週期-移動四季', '每股營業收入-移動四季',
       '每股營業利益-移動四季', '每股稅前淨益-移動四季', '每股稅後淨利-移動四季', '常續性EPS-移動四季',
       '每人營收-移動四季'],
      dtype='object')

In [ ]:
merge_data = stk_price.merge(fin_ann_date, left_on=['證券代碼', '年月日'], right_on=['公司碼', '發布日'], how = 'left').ffill().fillna(method = 'backfill')
merge_data

,證券代碼,年月日,開盤價(元),最高價(元),最低價(元),收盤價(元),成交量(千股),成交值(千元),報酬率％,週轉率％,...,每股稅後淨利-移動四季,常續性EPS-移動四季,每人營收,每人營收-移動四季,合併,發布日,會計開始月分,會計結束月分,期間,幣別
0,2330,1994-09-05,1.7203,1.7203,1.7203,1.7203,4.000,3.840000e+02,6.6667,0.0005,...,11.37368,10.35073,3859.45693,12058.02061,N,2006-05-02,2006-01-01,2006-03-31,3.0,NTD
1,2330,1994-09-06,1.8368,1.8368,1.8368,1.8368,1.000,1.020000e+02,6.7708,0.0001,...,11.37368,10.35073,3859.45693,12058.02061,N,2006-05-02,2006-01-01,2006-03-31,3.0,NTD
2,2330,1994-09-07,1.9623,1.9623,1.9623,1.9623,1.000,1.090000e+02,6.8293,0.0001,...,11.37368,10.35073,3859.45693,12058.02061,N,2006-05-02,2006-01-01,2006-03-31,3.0,NTD
3,2330,1994-09-08,2.0967,2.0967,2.0967,2.0967,2.000,2.340000e+02,6.8493,0.0003,...,11.37368,10.35073,3859.45693,12058.02061,N,2006-05-02,2006-01-01,2006-03-31,3.0,NTD
4,2330,1994-09-09,2.2400,2.2400,2.2400,2.2400,1.000,1.250000e+02,6.8376,0.0001,...,11.37368,10.35073,3859.45693,12058.02061,N,2006-05-02,2006-01-01,2006-03-31,3.0,NTD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7204,2330,2023-01-17,504.0000,504.0000,499.5000,503.0000,29443.522,1.478466e+07,-0.3960,0.1135,...,34.22223,34.41798,9410.95811,31872.37122,Y,2022-11-14,2022-07-01,2022-09-30,9.0,NTD
7205,2330,2023-01-30,542.0000,543.0000,534.0000,543.0000,148413.161,8.005716e+07,7.9523,0.5724,...,34.22223,34.41798,9410.95811,31872.37122,Y,2022-11-14,2022-07-01,2022-09-30,9.0,NTD
7206,2330,2023-01-31,537.0000,538.0000,521.0000,522.0000,79212.272,4.173694e+07,-3.8674,0.3055,...,34.22223,34.41798,9410.95811,31872.37122,Y,2022-11-14,2022-07-01,2022-09-30,9.0,NTD
7207,2330,2023-02-01,532.0000,533.0000,522.0000,530.0000,42539.626,2.245095e+07,1.5326,0.1641,...,34.22223,34.41798,9410.95811,31872.37122,Y,2022-11-14,2022-07-01,2022-09-30,9.0,NTD
7208,2330,2023-02-02,538.0000,542.0000,537.0000,540.0000,46523.592,2.509148e+07,1.8868,0.1794,...,34.22223,34.41798,9410.95811,31872.37122,Y,2022-11-14,2022-07-01,2022-09-30,9.0,NTD

In [ ]:
# 檢查是否有
merge_duplicate = merge_data.groupby(['證券代碼','年月日']).count()['次數'].reset_index()
merge_duplicate[merge_duplicate['次數']>1]

      證券代碼        年月日  次數
0     2330 1994-09-05   1
1     2330 1994-09-06   1
2     2330 1994-09-07   1
3     2330 1994-09-08   1
4     2330 1994-09-09   1
...    ...        ...  ..
7204  2330 2023-01-17   1
7205  2330 2023-01-30   1
7206  2330 2023-01-31   1
7207  2330 2023-02-01   1
7208  2330 2023-02-02   1

[7209 rows x 3 columns]

In [ ]:
merge_data[merge_data['年月日'] =='2006-05-02']

,證券代碼,年月日,開盤價(元),最高價(元),最低價(元),收盤價(元),成交量(千股),成交值(千元),報酬率％,週轉率％,...,每股稅後淨利-移動四季,常續性EPS-移動四季,每人營收,每人營收-移動四季,合併,發布日,會計開始月分,會計結束月分,期間,幣別
3076,2330,2006-05-02,32.6957,33.0885,32.6466,32.9903,50363.61,3372317.94,-1.3216,0.2036,...,11.37368,10.35073,3859.45693,12058.02061,N,2006-05-02,2006-01-01,2006-03-31,3.0,NTD

In [ ]:
fin_ann_date[fin_ann_date['發布日'] =='2006-05-02']

,公司碼,年月,次數,現金,約當現金,應收帳款,長期應收款,存貨,應付帳款,固定資產,...,每股稅後淨利-移動四季,常續性EPS-移動四季,每人營收,每人營收-移動四季,合併,發布日,會計開始月分,會計結束月分,期間,幣別
4,2330,2006-03-01,1,109989790.0,0.0,35779889.0,0.0,16901113.0,10873768.0,212522481.0,...,NaN,NaN,3859.45693,NaN,N,2006-05-02,2006-01-01,2006-03-31,3.0,NTD

In [ ]:
unique_date[unique_date['發布日'] =='2006-05-02']

    公司碼         年月  次數 合併        發布日     會計開始月分     會計結束月分  期間   幣別
2  2330 2006-03-01   1  N 2006-05-02 2006-01-01 2006-03-31   3  NTD

In [ ]:
announce_date[announce_date['發布日'] =='2006-05-02']

       公司碼         年月  次數 合併        發布日     會計開始月分     會計結束月分  期間   幣別
None
0     2330 2005-03-01   1  N 2006-05-02 2005-01-01 2005-03-31   3  NTD
4     2330 2006-03-01   1  N 2006-05-02 2006-01-01 2006-03-31   3  NTD

## 合併財務資料和股價資料
- ['2330','2303','2454']

In [3]:
listOfStocks = ['2330','2303','2454','1103','1101']
announce_date = tejapi.get('TWN/AINVFINQA',
 coid = listOfStocks,
 paginate = True,
  chinese_column_name=False,
  opts = {})
announce_date

,coid,mdate,fin_od,merg,a_dd,sym8,eym8,term,currency
None,,,,,,,,,
0,1101,2005-03-01,1,N,2006-04-30,2005-01-01,2005-03-31,3,NTD
1,1101,2005-06-01,1,Y,2006-08-31,2005-04-01,2005-06-30,6,NTD
2,1101,2005-09-01,1,N,2006-10-31,2005-07-01,2005-09-30,9,NTD
3,1101,2005-12-01,1,Y,2007-04-24,2005-10-01,2005-12-31,12,NTD
4,1101,2006-03-01,1,N,2006-04-30,2006-01-01,2006-03-31,3,NTD
...,...,...,...,...,...,...,...,...,...
510,2454,2021-09-01,2,Y,2022-11-11,2021-07-01,2021-09-30,9,NTD
511,2454,2021-12-01,1,Y,2022-02-25,2021-10-01,2021-12-31,12,NTD
512,2454,2022-03-01,1,Y,2022-05-13,2022-01-01,2022-03-31,3,NTD
513,2454,2022-06-01,1,Y,2022-08-12,2022-04-01,2022-06-30,6,NTD
514,2454,2022-09-01,1,Y,2022-11-11,2022-07-01,2022-09-30,9,NTD

In [4]:
announce_date[announce_date['a_dd']=='2007-04-30']

,coid,mdate,fin_od,merg,a_dd,sym8,eym8,term,currency
None,,,,,,,,,
8,1101,2007-03-01,1,N,2007-04-30,2007-01-01,2007-03-31,3,NTD
114,1103,2007-03-01,1,N,2007-04-30,2007-01-01,2007-03-31,3,NTD
213,2303,2005-12-01,1,Y,2007-04-30,2005-10-01,2005-12-31,12,NTD
217,2303,2006-12-01,1,Y,2007-04-30,2006-10-01,2006-12-31,12,NTD
218,2303,2007-03-01,1,N,2007-04-30,2007-01-01,2007-03-31,3,NTD

In [5]:
unique_date = get_announce_date(ticker=listOfStocks)
unique_date

,coid,mdate,fin_od,merg,a_dd,sym8,eym8,term,currency
0,1101,2006-03-01,1,N,2006-04-30,2006-01-01,2006-03-31,3,NTD
1,1101,2006-06-01,1,Y,2006-08-31,2006-04-01,2006-06-30,6,NTD
2,1101,2006-09-01,1,N,2006-10-31,2006-07-01,2006-09-30,9,NTD
3,1101,2006-12-01,1,Y,2007-04-24,2006-10-01,2006-12-31,12,NTD
4,1101,2007-03-01,1,N,2007-04-30,2007-01-01,2007-03-31,3,NTD
...,...,...,...,...,...,...,...,...,...
307,2454,2021-09-01,1,Y,2021-11-12,2021-07-01,2021-09-30,9,NTD
308,2454,2021-12-01,1,Y,2022-02-25,2021-10-01,2021-12-31,12,NTD
309,2454,2022-03-01,1,Y,2022-05-13,2022-01-01,2022-03-31,3,NTD
310,2454,2022-06-01,1,Y,2022-08-12,2022-04-01,2022-06-30,6,NTD
311,2454,2022-09-01,1,Y,2022-11-11,2022-07-01,2022-09-30,9,NTD

In [6]:
unique_date[unique_date['a_dd']=='2007-04-30']

,coid,mdate,fin_od,merg,a_dd,sym8,eym8,term,currency
4,1101,2007-03-01,1,N,2007-04-30,2007-01-01,2007-03-31,3,NTD
68,1103,2007-03-01,1,N,2007-04-30,2007-01-01,2007-03-31,3,NTD
132,2303,2007-03-01,1,N,2007-04-30,2007-01-01,2007-03-31,3,NTD

In [7]:
fin_data = pd.DataFrame()
for i in listOfStocks:
   fin = tejapi.get('TWN/AINVFINQ',
   coid = i,
   paginate = True,
   chinese_column_name=False,
      opts= {'pivot':True, 'columns':[]})
   fin_data = pd.concat([fin_data, fin])
fin_data

,coid,mdate,fin_od,BP11,BP12,BP21,BP22,BP31,BP41,BP51,...,M304,R305,M305,R306,M306,R316,M316,M317,R834,M834
None,,,,,,,,,,,,,,,,,,,,,
0,2330,2005-03-01,1,60218990.0,0.0,22428991.0,0.0,13428985.0,8207745.0,229853709.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2984.40675,NaN
1,2330,2005-06-01,1,88405154.0,0.0,32095014.0,0.0,15158776.0,7605043.0,257006435.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2914.70216,NaN
2,2330,2005-09-01,1,58467326.0,0.0,37248082.0,0.0,15070064.0,10042040.0,218909371.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3419.32318,NaN
3,2330,2005-12-01,1,96483707.0,0.0,38477534.0,0.0,17728303.0,11164521.0,244823292.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3787.60916,NaN
4,2330,2006-03-01,1,109989790.0,0.0,35779889.0,0.0,16901113.0,10873768.0,212522481.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3859.45693,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99,1101,2021-09-01,2,59958809.0,0.0,36493940.0,24928581.0,11238700.0,8274800.0,114975260.0,...,17.37080,0.62964,3.82861,0.76610,4.63193,0.69183,3.84134,3.19310,2475.72592,9797.59403
100,1101,2021-12-01,1,91121942.0,0.0,35940929.0,24334423.0,13412511.0,10023071.0,120950826.0,...,17.47549,0.76390,3.23032,1.09915,4.25748,0.80996,3.46130,2.87099,2525.91199,8971.70832
101,1101,2022-03-01,1,98040416.0,0.0,33801330.0,24108219.0,13552203.0,11279929.0,127245067.0,...,17.62827,0.03390,2.57729,0.19136,3.65621,0.13983,2.99213,2.49143,1925.52686,9050.14341
102,1101,2022-06-01,1,100497555.0,0.0,29399946.0,23198379.0,18318975.0,13304491.0,130731263.0,...,17.16986,-0.32777,1.09956,-0.07098,1.98550,-0.15358,1.48792,1.31791,2110.28690,8814.80027
103,1101,2022-09-01,1,95367543.0,0.0,33218170.0,22101820.0,17682787.0,13906734.0,137067245.0,...,16.24229,0.09316,0.52055,0.31224,1.42116,0.24325,0.96725,0.83028,2608.58570,9170.31146

In [8]:
# merge announce_date with financial report
fin_ann_date = fin_data.merge(unique_date, left_on=['coid', 'mdate', 'fin_od'], right_on= ['coid', 'mdate', 'fin_od'], how='left')
fin_ann_date

,coid,mdate,fin_od,BP11,BP12,BP21,BP22,BP31,BP41,BP51,...,M316,M317,R834,M834,merg,a_dd,sym8,eym8,term,currency
0,2330,2005-03-01,1,60218990.0,0.0,22428991.0,0.0,13428985.0,8207745.0,229853709.0,...,NaN,NaN,2984.40675,NaN,NaN,NaT,NaT,NaT,NaN,NaN
1,2330,2005-06-01,1,88405154.0,0.0,32095014.0,0.0,15158776.0,7605043.0,257006435.0,...,NaN,NaN,2914.70216,NaN,NaN,NaT,NaT,NaT,NaN,NaN
2,2330,2005-09-01,1,58467326.0,0.0,37248082.0,0.0,15070064.0,10042040.0,218909371.0,...,NaN,NaN,3419.32318,NaN,N,2006-10-30,2005-07-01,2005-09-30,9.0,NTD
3,2330,2005-12-01,1,96483707.0,0.0,38477534.0,0.0,17728303.0,11164521.0,244823292.0,...,NaN,NaN,3787.60916,NaN,Y,2007-02-26,2005-10-01,2005-12-31,12.0,NTD
4,2330,2006-03-01,1,109989790.0,0.0,35779889.0,0.0,16901113.0,10873768.0,212522481.0,...,NaN,NaN,3859.45693,NaN,N,2006-05-02,2006-01-01,2006-03-31,3.0,NTD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
510,1101,2021-09-01,2,59958809.0,0.0,36493940.0,24928581.0,11238700.0,8274800.0,114975260.0,...,3.84134,3.19310,2475.72592,9797.59403,NaN,NaT,NaT,NaT,NaN,NaN
511,1101,2021-12-01,1,91121942.0,0.0,35940929.0,24334423.0,13412511.0,10023071.0,120950826.0,...,3.46130,2.87099,2525.91199,8971.70832,Y,2022-02-25,2021-10-01,2021-12-31,12.0,NTD
512,1101,2022-03-01,1,98040416.0,0.0,33801330.0,24108219.0,13552203.0,11279929.0,127245067.0,...,2.99213,2.49143,1925.52686,9050.14341,Y,2022-05-10,2022-01-01,2022-03-31,3.0,NTD
513,1101,2022-06-01,1,100497555.0,0.0,29399946.0,23198379.0,18318975.0,13304491.0,130731263.0,...,1.48792,1.31791,2110.28690,8814.80027,Y,2022-08-12,2022-04-01,2022-06-30,6.0,NTD
514,1101,2022-09-01,1,95367543.0,0.0,33218170.0,22101820.0,17682787.0,13906734.0,137067245.0,...,0.96725,0.83028,2608.58570,9170.31146,Y,2022-11-10,2022-07-01,2022-09-30,9.0,NTD

In [9]:
# 營業日
days = pd.date_range(start='2005-01-01', end=datetime.datetime.now(), freq='D')
days = pd.DataFrame({'all_dates':days})
# 結合發布日(announce_date)以及營業日(bussiness days)
fin_BD = days.merge(fin_ann_date, left_on='all_dates', right_on = 'a_dd', how = 'left').ffill()
fin_BD # [df['年月']>=df['日曆日']] # [~df['公司碼'].isna()]

,all_dates,coid,mdate,fin_od,BP11,BP12,BP21,BP22,BP31,BP41,...,M316,M317,R834,M834,merg,a_dd,sym8,eym8,term,currency
0,2005-01-01,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaT,NaN,NaN
1,2005-01-02,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaT,NaN,NaN
2,2005-01-03,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaT,NaN,NaN
3,2005-01-04,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaT,NaN,NaN
4,2005-01-05,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaT,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6693,2023-02-06,2330,2022-09-01,1.0,1.296013e+09,0.0,261538308.0,0.0,218335874.0,62018224.0,...,34.22223,34.41798,9410.95811,31872.37122,Y,2022-11-14,2022-07-01,2022-09-30,9.0,NTD
6694,2023-02-07,2330,2022-09-01,1.0,1.296013e+09,0.0,261538308.0,0.0,218335874.0,62018224.0,...,34.22223,34.41798,9410.95811,31872.37122,Y,2022-11-14,2022-07-01,2022-09-30,9.0,NTD
6695,2023-02-08,2330,2022-09-01,1.0,1.296013e+09,0.0,261538308.0,0.0,218335874.0,62018224.0,...,34.22223,34.41798,9410.95811,31872.37122,Y,2022-11-14,2022-07-01,2022-09-30,9.0,NTD
6696,2023-02-09,2330,2022-09-01,1.0,1.296013e+09,0.0,261538308.0,0.0,218335874.0,62018224.0,...,34.22223,34.41798,9410.95811,31872.37122,Y,2022-11-14,2022-07-01,2022-09-30,9.0,NTD
6697,2023-02-10,2330,2022-09-01,1.0,1.296013e+09,0.0,261538308.0,0.0,218335874.0,62018224.0,...,34.22223,34.41798,9410.95811,31872.37122,Y,2022-11-14,2022-07-01,2022-09-30,9.0,NTD

In [14]:
x = fin_BD.groupby(['all_dates', 'coid', 'mdate']).count()['fin_od']
x[x > 1]
#fin_BD.loc[index]

Series([], Name: fin_od, dtype: int64)

In [13]:
fin_BD[fin_BD['all_dates'] == '2007-04-30']

,all_dates,coid,mdate,fin_od,BP11,BP12,BP21,BP22,BP31,BP41,...,M316,M317,R834,M834,merg,a_dd,sym8,eym8,term,currency
856,2007-04-30,2303,2007-03-01,1.0,80988902.0,0.0,12850865.0,0.0,9957197.0,4653399.0,...,NaN,NaN,1716.37950,8247.84823,N,2007-04-30,2007-01-01,2007-03-31,3.0,NTD
857,2007-04-30,1103,2007-03-01,1.0,1686228.0,0.0,466631.0,0.0,35417.0,258699.0,...,NaN,NaN,8056.83168,104486.00990,N,2007-04-30,2007-01-01,2007-03-31,3.0,NTD
858,2007-04-30,1101,2007-03-01,1.0,3999811.0,0.0,4490090.0,0.0,1688579.0,2336620.0,...,NaN,NaN,4639.29675,46934.69819,N,2007-04-30,2007-01-01,2007-03-31,3.0,NTD

In [17]:
# stock price 
stk_price = pd.DataFrame()
for i in listOfStocks:
  stk = tejapi.get('TWN/APRCD1',
  coid = i,
  paginate = True,
  chinese_column_name=False)
  stk_price = pd.concat([stk_price, stk])
stk_price = stk_price.reset_index(drop=True)
stk_price

,coid,mdate,open_adj,high_adj,low_adj,close_adj,volume,amount,roi,turnover,...,tej_cdiv,clschg,hmlpct,refprc,u_limit,d_limit,xattn1,xattn2,xstat1,pmkt
0,2330,1994-09-05,1.7203,1.7203,1.7203,1.7203,4.000,384.000,6.6667,0.0005,...,NaN,NaN,NaN,96.00,102.50,89.50,,,,TSE
1,2330,1994-09-06,1.8368,1.8368,1.8368,1.8368,1.000,102.000,6.7708,0.0001,...,NaN,6.50,0.0000,102.50,109.50,95.50,,,,TSE
2,2330,1994-09-07,1.9623,1.9623,1.9623,1.9623,1.000,109.000,6.8293,0.0001,...,NaN,7.00,0.0000,109.50,117.00,102.00,,,,TSE
3,2330,1994-09-08,2.0967,2.0967,2.0967,2.0967,2.000,234.000,6.8493,0.0003,...,NaN,7.50,0.0000,117.00,125.00,109.00,,,,TSE
4,2330,1994-09-09,2.2400,2.2400,2.2400,2.2400,1.000,125.000,6.8376,0.0001,...,NaN,8.00,0.0000,125.00,133.50,116.50,,,,TSE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50469,1101,2023-02-03,36.7500,36.7500,36.3000,36.4500,16800.332,612061.416,-0.9511,0.2348,...,2.3466,-0.35,1.2228,36.45,40.05,32.85,,,,TSE
50470,1101,2023-02-06,36.4000,36.4500,36.0000,36.1500,18914.974,684900.126,-0.8230,0.2643,...,2.3660,-0.30,1.2346,36.15,39.75,32.55,,,,TSE
50471,1101,2023-02-07,36.2000,36.6500,36.2000,36.6500,12818.745,468441.190,1.3831,0.1791,...,2.3338,0.50,1.2448,36.65,40.30,33.00,,,,TSE
50472,1101,2023-02-08,36.5500,36.8000,36.5000,36.7500,12201.334,447257.491,0.2729,0.1705,...,2.3274,0.10,0.8186,36.75,40.40,33.10,,,,TSE
50473,1101,2023-02-09,36.7000,36.8000,36.5500,36.6000,11379.279,417204.418,-0.4082,0.1590,...,2.3369,-0.15,0.6803,36.60,40.25,32.95,,,,TSE

In [18]:
merge_data = stk_price.merge(fin_BD, left_on=['coid', 'mdate'], right_on=['coid', 'all_dates'], how = 'left')#.ffill()#.fillna(method = 'backfill')
merge_data

,coid,mdate_x,open_adj,high_adj,low_adj,close_adj,volume,amount,roi,turnover,...,M316,M317,R834,M834,merg,a_dd,sym8,eym8,term,currency
0,2330,1994-09-05,1.7203,1.7203,1.7203,1.7203,4.000,384.000,6.6667,0.0005,...,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaT,NaN,NaN
1,2330,1994-09-06,1.8368,1.8368,1.8368,1.8368,1.000,102.000,6.7708,0.0001,...,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaT,NaN,NaN
2,2330,1994-09-07,1.9623,1.9623,1.9623,1.9623,1.000,109.000,6.8293,0.0001,...,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaT,NaN,NaN
3,2330,1994-09-08,2.0967,2.0967,2.0967,2.0967,2.000,234.000,6.8493,0.0003,...,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaT,NaN,NaN
4,2330,1994-09-09,2.2400,2.2400,2.2400,2.2400,1.000,125.000,6.8376,0.0001,...,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaT,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50469,1101,2023-02-03,36.7500,36.7500,36.3000,36.4500,16800.332,612061.416,-0.9511,0.2348,...,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaT,NaN,NaN
50470,1101,2023-02-06,36.4000,36.4500,36.0000,36.1500,18914.974,684900.126,-0.8230,0.2643,...,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaT,NaN,NaN
50471,1101,2023-02-07,36.2000,36.6500,36.2000,36.6500,12818.745,468441.190,1.3831,0.1791,...,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaT,NaN,NaN
50472,1101,2023-02-08,36.5500,36.8000,36.5000,36.7500,12201.334,447257.491,0.2729,0.1705,...,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaT,NaN,NaN
50473,1101,2023-02-09,36.7000,36.8000,36.5500,36.6000,11379.279,417204.418,-0.4082,0.1590,...,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaT,NaN,NaN

In [ ]:
merge_data = merge_data.groupby('證券代碼').ffill()
merge_data

,年月日,開盤價(元),最高價(元),最低價(元),收盤價(元),成交量(千股),成交值(千元),報酬率％,週轉率％,流通在外股數(千股),...,每股稅後淨利-移動四季,常續性EPS-移動四季,每人營收,每人營收-移動四季,合併,發布日,會計開始月分,會計結束月分,期間,幣別
0,1994-09-05,1.7203,1.7203,1.7203,1.7203,4.000,384.000,6.6667,0.0005,780000,...,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaT,NaN,NaN
1,1994-09-06,1.8368,1.8368,1.8368,1.8368,1.000,102.000,6.7708,0.0001,780000,...,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaT,NaN,NaN
2,1994-09-07,1.9623,1.9623,1.9623,1.9623,1.000,109.000,6.8293,0.0001,780000,...,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaT,NaN,NaN
3,1994-09-08,2.0967,2.0967,2.0967,2.0967,2.000,234.000,6.8493,0.0003,780000,...,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaT,NaN,NaN
4,1994-09-09,2.2400,2.2400,2.2400,2.2400,1.000,125.000,6.8376,0.0001,780000,...,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaT,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50459,2023-02-01,36.4500,36.7500,36.3000,36.7500,15215.064,557059.198,1.3793,0.2126,7156182,...,0.96725,0.83028,2608.5857,9170.31146,Y,2022-11-10,2022-07-01,2022-09-30,9.0,NTD
50460,2023-02-02,36.8500,36.9000,36.5500,36.8000,14814.809,544700.449,0.1361,0.2070,7156182,...,0.96725,0.83028,2608.5857,9170.31146,Y,2022-11-10,2022-07-01,2022-09-30,9.0,NTD
50461,2023-02-03,36.7500,36.7500,36.3000,36.4500,16800.332,612061.416,-0.9511,0.2348,7156182,...,0.96725,0.83028,2608.5857,9170.31146,Y,2022-11-10,2022-07-01,2022-09-30,9.0,NTD
50462,2023-02-06,36.4000,36.4500,36.0000,36.1500,18914.974,684900.126,-0.8230,0.2643,7156182,...,0.96725,0.83028,2608.5857,9170.31146,Y,2022-11-10,2022-07-01,2022-09-30,9.0,NTD
50463,2023-02-07,36.2000,36.6500,36.2000,36.6500,12818.745,468441.190,1.3831,0.1791,7156182,...,0.96725,0.83028,2608.5857,9170.31146,Y,2022-11-10,2022-07-01,2022-09-30,9.0,NTD

In [ ]:
# 檢查
# merge_data[~merge_data['發布日'].isna()]
merge_data[merge_data['發布日']>merge_data['年月日']]

Empty DataFrame
Columns: [年月日, 開盤價(元), 最高價(元), 最低價(元), 收盤價(元), 成交量(千股), 成交值(千元), 報酬率％, 週轉率％, 流通在外股數(千股), 市值(百萬元), 最後揭示買價, 最後揭示賣價, 報酬率-Ln, 市值比重％, 成交值比重％, 成交筆數(筆), 本益比-TSE, 本益比-TEJ, 股價淨值比-TSE, 股價淨值比-TEJ, 漲跌停, 股價營收比-TEJ, 股利殖利率-TSE, 現金股利率, 股價漲跌(元), 高低價差%, 次日開盤參考價, 次日漲停價, 次日跌停價, 注意股票(A), 處置股票(D), 全額交割(Y), 市場別, 日曆日, 公司碼, 年月, 次數, 現金, 約當現金, 應收帳款, 長期應收款, 存貨, 應付帳款, 固定資產, 生物資產, 無形資產, 油氣資產, 預付款, 其他應收款, 預收款, 其他應付款, 待出售非流動資產, 待出售資產相關負債, 其他營運流動資產, 其他營運非流動資產, 其他營運流動負債, 其他營運非流動負債, 金融資產流動, 金融負債流動, 金融資產非流動, 金融負債非流動, 策略性投資, 投資性不動產, 資金貸與(流動), 資金貸與(非流動), 金融借款(流動), 金融借款(非流動), 非金融借款(流動), 非金融借款(非流動), 或有負債, 普通股股本, 資本公積, 保留盈餘, 特別股股本, 非控制權益, 其他權益, 流動資產合計, 非流動資產合計, 資產總計, 流動負債合計, 非流動負債合計, 負債總額, 股東權益總計, 負債及股東權益總計, 長短期借款, 可用資金, 嚴格速動資產, 速動資產, 生財設備, 長短期應收帳款, 營業收入, 營業總收入, 異業營業收入, 營業成本, 營業總成本, 異業營業成本, 營業費用, 處分資產損益, 固定資產減損, ...]
Index: []

[0 rows x 255 columns]

## 月營收合併股價

In [13]:
list_of_Stocks = ['2330','2303','2454', '2882', '2881']
month_sales = pd.DataFrame()
for i in list_of_Stocks:
    month_sale = tejapi.get('TWN/APISALE', coid = i)
    month_sales = pd.concat([month_sales, month_sale])
month_sales

,coid,mdate,annd_s,d0001,d0002,d0003,d0004,d0005,d0006,d0007,...,t8133,t8134,r25,r26,r26a,d0025,d0026,d0027,r19,r27
None,,,,,,,,,,,,,,,,,,,,,
0,2330,2013-01-01,2013-02-08,47438687,34606486,37.08,27.68,47438687,34606486,37.08,...,128887963,NaN,NaN,-1.95,-9.82,25928617,1.83,1.83,20.04,4.97
1,2330,2013-02-01,2013-03-08,41182084,33893476,21.50,-13.19,88620771,68499962,29.37,...,125775046,NaN,NaN,-2.42,-8.65,25928617,1.59,3.42,20.32,4.85
2,2330,2013-03-01,2013-04-10,44134225,37114869,18.91,7.17,132754996,105614831,25.70,...,132754996,105614831.0,25.70,5.55,1.00,25928617,1.70,5.12,20.59,5.12
3,2330,2013-04-01,2013-05-10,50070645,40542396,23.50,13.45,182825641,146157227,25.09,...,135386954,111550741.0,21.37,1.98,5.04,25928617,1.93,7.05,20.96,5.22
4,2330,2013-05-01,2013-06-10,51787926,44177010,17.23,3.43,234613567,190334237,23.26,...,145992796,121834275.0,19.83,7.83,16.07,25928617,2.00,9.05,21.25,5.63
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,2881,2022-09-01,2022-10-07,23259981,28305915,-17.83,29.72,290605302,379170854,-23.36,...,64578988,109879720.0,-41.23,-14.67,-29.08,12395213,1.88,23.44,32.08,5.21
117,2881,2022-10-01,2022-11-10,-5859934,30385995,-119.28,-125.19,284745367,409556849,-30.47,...,35331651,96742270.0,-63.48,-45.29,-54.90,12395213,-0.47,22.97,29.15,2.85
118,2881,2022-11-01,2022-12-09,-28846346,29907638,-196.45,-392.26,255899022,439464488,-41.77,...,-11446299,88599548.0,-112.92,-132.40,-115.12,12395213,-2.33,20.64,24.41,-0.92
119,2881,2022-12-01,2023-01-10,3343545,46705053,-92.84,111.59,259242566,486169540,-46.68,...,-31362735,106998686.0,-129.31,-174.00,-148.56,12395213,0.27,20.91,20.91,-2.53
120,2881,2023-01-01,2023-02-10,16144741,61439359,-73.72,382.86,16144741,61439359,-73.72,...,-9358060,138052050.0,-106.78,70.16,-126.49,12395213,1.30,1.30,17.26,-0.75

In [ ]:
pd.date_range('')

In [14]:
month_sales['mdate'].min()

Timestamp('2013-01-01 00:00:00')

## 集保合併股價

In [2]:
rand_series = np.random.randint(0,len(para.fin_company_group),5)
fin_test_c = [para.fin_company_group[i] for i in rand_series]
test_columns = list(set(para.trading_columns_group[:5]+ para.share_dist_group[:5]+para.monthly_revenue_group[:5]+fin_test_c))
fin_test_c, sorted(test_columns)

(['r105', 'isnip', 'fin_ind', 'fin_ind', 'no'],
 ['annd_s',
  'coid',
  'd0001',
  'd0002',
  'edate1',
  'fc_s',
  'fin_ind',
  'high_d',
  'isnip',
  'mdate',
  'mkt',
  'no',
  'open_d',
  'r105'])

In [5]:
list_of_Stocks = ['2330','2303','2454', '2882', '2881']
tables = triggers(list_of_Stocks, test_columns,transfer_to_chinese = False)

In [12]:
mm = tables['monthly_rev']
mm[~mm['annd_s'].isna()]

      all_dates      mdate       d0002  coid     annd_s       d0001
35   2013-02-05 2013-01-01  35066951.0  2882 2013-02-05  42026866.0
36   2013-02-06 2013-01-01  35066951.0  2882 2013-02-05  42026866.0
37   2013-02-07 2013-01-01   5157714.0  2454 2013-02-07   8452573.0
38   2013-02-08 2013-01-01  34606486.0  2330 2013-02-08  47438687.0
39   2013-02-08 2013-01-01   8844488.0  2303 2013-02-08   9452116.0
...         ...        ...         ...   ...        ...         ...
4009 2023-02-18 2023-01-01  61439359.0  2881 2023-02-10  16144741.0
4010 2023-02-19 2023-01-01  61439359.0  2881 2023-02-10  16144741.0
4011 2023-02-20 2023-01-01  61439359.0  2881 2023-02-10  16144741.0
4012 2023-02-21 2023-01-01  61439359.0  2881 2023-02-10  16144741.0
4013 2023-02-22 2023-01-01  61439359.0  2881 2023-02-10  16144741.0

[3979 rows x 6 columns]

In [3]:
# list_of_Stocks = ['2330','2303','2454', '2882', '2881']
# tables = triggers(list_of_Stocks, test_columns,transfer_to_chinese = False)
# trigger_tables = [i for i in tables.keys() if i in ['fin_data', 'stk_price', 'share_dist','monthly_rev','overbought']]
# # 根據 OD 進行排序
# trigger_tables.sort(key = lambda x: para.map_table.loc[para.map_table['TABLE_NAME']==x, 'OD'].item())
# trigger_tables

In [4]:
list_of_Stocks = ['2330','2303','2454', '2882', '2881']
all_tables = get_history_data(ticker=list_of_Stocks,columns= test_columns, transfer_to_chinese=False)

Index(['open_d', 'mdate', 'mkt', 'high_d', 'coid'], dtype='object')
Index(['open_d', 'mdate', 'mkt', 'high_d', 'coid', 'all_dates', 'isnip_A',
       'sem', 'no', 'r105_A', 'fin_type', 'fin_ind_A', 'annd', 'isnip_Q',
       'r105_Q', 'fin_ind_Q', 'isnip_TTM', 'r105_TTM', 'fin_ind_TTM'],
      dtype='object')
Index(['open_d', 'mdate', 'mkt', 'high_d', 'coid', 'all_dates', 'isnip_A',
       'sem', 'no', 'r105_A', 'fin_type', 'fin_ind_A', 'annd', 'isnip_Q',
       'r105_Q', 'fin_ind_Q', 'isnip_TTM', 'r105_TTM', 'fin_ind_TTM', 'annd_s',
       'd0001', 'd0002'],
      dtype='object')
Index(['open_d', 'mdate', 'mkt', 'high_d', 'coid', 'all_dates', 'isnip_A',
       'sem', 'no', 'r105_A', 'fin_type', 'fin_ind_A', 'annd', 'isnip_Q',
       'r105_Q', 'fin_ind_Q', 'isnip_TTM', 'r105_TTM', 'fin_ind_TTM', 'annd_s',
       'd0001', 'd0002', 'edate1', 'fc_s'],
      dtype='object')

In [6]:
all_tables

,open_d,mdate,mkt,high_d,coid,all_dates,isnip_A,sem,no,r105_A,...,r105_Q,fin_ind_Q,isnip_TTM,r105_TTM,fin_ind_TTM,annd_s,d0001,d0002,edate1,fc_s
0,97.6,2013-01-02,TWSE,99.9,2330,NaT,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaT,NaN
1,100.5,2013-01-03,TWSE,102.0,2330,NaT,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaT,NaN
2,100.5,2013-01-04,TWSE,101.5,2330,NaT,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaT,NaN
3,101.0,2013-01-07,TWSE,101.0,2330,NaT,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaT,NaN
4,99.6,2013-01-08,TWSE,100.0,2330,NaT,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaT,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12395,60.0,2023-02-15,TWSE,60.3,2881,2023-01-11,46720000.0,4,001,58.54,...,60.43,O,46720000.0,57.3,O,2023-01-10,3343545.0,46705053.0,2023-01-02,12395212.0
12396,59.6,2023-02-16,TWSE,60.0,2881,2023-01-11,46720000.0,4,001,58.54,...,60.43,O,46720000.0,57.3,O,2023-01-10,3343545.0,46705053.0,2023-01-02,12395212.0
12397,59.8,2023-02-17,TWSE,60.3,2881,2023-01-11,46720000.0,4,001,58.54,...,60.43,O,46720000.0,57.3,O,2023-01-10,3343545.0,46705053.0,2023-01-02,12395212.0
12398,60.0,2023-02-20,TWSE,61.1,2881,2023-01-11,46720000.0,4,001,58.54,...,60.43,O,46720000.0,57.3,O,2023-01-10,3343545.0,46705053.0,2023-01-02,12395212.0
12399,60.6,2023-02-21,TWSE,60.6,2881,2023-01-11,46720000.0,4,001,58.54,...,60.43,O,46720000.0,57.3,O,2023-01-10,3343545.0,46705053.0,2023-01-02,12395212.0

In [6]:
table_keys =  para.map_table.merge(para.merge_keys)
i = 0
left_keys = table_keys.loc[table_keys['TABLE_NAME']==trigger_tables[i], 'KEYS'].tolist()
right_keys = table_keys.loc[table_keys['TABLE_NAME']==trigger_tables[i+1], 'KEYS'].tolist()
data = consecutive_merge(tables, trigger_tables[0],trigger_tables[1], left_keys, right_keys, i = 0)
data

        mkt  open_d  high_d      mdate  coid
0      TWSE    97.6    99.9 2013-01-02  2330
1      TWSE   100.5   102.0 2013-01-03  2330
2      TWSE   100.5   101.5 2013-01-04  2330
3      TWSE   101.0   101.0 2013-01-07  2330
4      TWSE    99.6   100.0 2013-01-08  2330
...     ...     ...     ...        ...   ...
12390  TWSE    60.0    60.2 2023-02-14  2881
12391  TWSE    60.0    60.3 2023-02-15  2881
12392  TWSE    59.6    60.0 2023-02-16  2881
12393  TWSE    59.8    60.3 2023-02-17  2881
12394  TWSE    60.0    61.1 2023-02-20  2881

[12395 rows x 5 columns]

In [8]:
tejapi.table_info('TWN/AFESTM1')['filters']

['coid',
 'mdate',
 'key3',
 'no',
 'sem',
 'fin_type',
 'curr',
 'annd',
 'fin_ind',
 'ip12',
 'gm',
 'isoi',
 'isibt',
 'isni',
 'isnip',
 'r306',
 'eps',
 'r105',
 'r106',
 'r107',
 'r108',
 'r401',
 'r402',
 'r403',
 'r404',
 'r405']

## 籌碼資料合併股價