In [1]:
import tejapi 
tejapi.ApiConfig.api_base="http://10.10.10.66"
tejapi.ApiConfig.api_key = "3jUCETU2KiPwGJeyETYOQd1TCoDoxX"
tejapi.ApiConfig.ignoretz = True
import pandas as pd
import numpy as np
import datetime
import matplotlib.pyplot as plt
from All_functions import *

## 測試API

In [2]:
# random select 5 colunms from the fin_company_group
rand_series = np.random.randint(0,len(para.table_columns),5)
fin_test_c = para.table_columns.loc[rand_series,'COLUMNS']
test_columns = list(set(fin_test_c))
sorted(test_columns)

['edate2', 'gm', 'shrp_o1000', 't8133', 'tot_sell']

In [3]:
search_table(test_columns)

        COLUMNS         TABLE_NAMES
10           gm        fin_self_acc
36           gm    fin_board_select
100       t8133         month_sales
141    tot_sell      bargaing_chips
178      edate2  share_distribution
196  shrp_o1000  share_distribution
227          gm         fin_auditor

In [2]:
stks = ['1101', '2882', '2330']
trigger_tables = triggers(stks,columns=['low_d', 'd0001','shrm_8_10'])

stk_price
month_sales
share_distribution

In [4]:
trigger_tables.keys()

dict_keys(['ticker', 'columns', 'start', 'end', 'transfer_to_chinese', 'trading_calendar', 'trigger_tables', 'table', 'selected_columns', 'api_code', 'api_table', 'stk_price', 'month_sales', 'share_distribution'])

In [3]:
trigger_tables['month_sales'][~trigger_tables['month_sales']['d0001'].isna()]

      all_dates  coid     annd_s        d0001
48   2013-02-18  1101 2013-02-18    9134465.0
49   2013-02-19  1101 2013-02-18    9134465.0
50   2013-02-20  1101 2013-02-18    9134465.0
51   2013-02-21  1101 2013-02-18    9134465.0
52   2013-02-22  1101 2013-02-18    9134465.0
...         ...   ...        ...          ...
3702 2023-02-20  2330 2023-02-10  200050544.0
3703 2023-02-21  2330 2023-02-10  200050544.0
3704 2023-02-22  2330 2023-02-10  200050544.0
3705 2023-02-23  2330 2023-02-10  200050544.0
3706 2023-02-24  2330 2023-02-10  200050544.0

[11000 rows x 4 columns]

In [7]:
trigger_tables['share_distribution'][~trigger_tables['share_distribution']['shrm_8_10'].isna()]

      all_dates  coid      mdate  shrm_8_10
34   2013-02-04  1101 2013-02-04       59.0
35   2013-02-05  1101 2013-02-04       59.0
36   2013-02-06  1101 2013-02-04       59.0
37   2013-02-07  1101 2013-02-04       59.0
38   2013-02-08  1101 2013-02-04       59.0
...         ...   ...        ...        ...
3702 2023-02-20  2330 2023-02-13      212.0
3703 2023-02-21  2330 2023-02-13      212.0
3704 2023-02-22  2330 2023-02-13      212.0
3705 2023-02-23  2330 2023-02-13      212.0
3706 2023-02-24  2330 2023-02-13      212.0

[11043 rows x 4 columns]

In [12]:
trigger_tables['stk_price']

       low_d  coid      mdate
None
0      38.65  1101 2013-01-02
1      38.75  1101 2013-01-03
2      38.60  1101 2013-01-04
3      38.65  1101 2013-01-07
4      38.20  1101 2013-01-08
...      ...   ...        ...
2477  516.00  2330 2023-02-17
2478  511.00  2330 2023-02-20
2479  513.00  2330 2023-02-21
2480  505.00  2330 2023-02-22
2481  510.00  2330 2023-02-23

[7446 rows x 3 columns]

In [2]:
stks = ['1101', '2882', '2330']
cols = ['low_d', 'd0001','shrm_8_10']
all_tables = get_history_data(ticker=stks, columns= cols, transfer_to_chinese=False)

stk_price
month_sales
share_distribution

In [4]:
all_tables[~all_tables['all_dates'].isna()]

      coid      mdate  low_d  all_dates        d0001     edate1  shrm_8_10
26    1101 2013-02-18   38.8 2013-02-18    9134465.0 2013-02-04       59.0
27    1101 2013-02-19   38.7 2013-02-19    9134465.0 2013-02-04       59.0
28    1101 2013-02-20   38.1 2013-02-20    9134465.0 2013-02-04       59.0
29    1101 2013-02-21   37.4 2013-02-21    9134465.0 2013-02-04       59.0
30    1101 2013-02-22   37.2 2013-02-22    9134465.0 2013-02-04       59.0
...    ...        ...    ...        ...          ...        ...        ...
7467  2330 2023-02-17  516.0 2023-02-17  200050544.0 2023-02-13      212.0
7468  2330 2023-02-20  511.0 2023-02-20  200050544.0 2023-02-13      212.0
7469  2330 2023-02-21  513.0 2023-02-21  200050544.0 2023-02-13      212.0
7470  2330 2023-02-22  505.0 2023-02-22  200050544.0 2023-02-13      212.0
7471  2330 2023-02-23  510.0 2023-02-23  200050544.0 2023-02-13      212.0

[7396 rows x 7 columns]

In [6]:
all_tables[(all_tables['coid']=='2330')&(~all_tables['d0001'].isna())]

      coid      mdate  low_d  all_dates        d0001     edate1  shrm_8_10
5016  2330 2013-02-18  106.5 2013-02-18   47438687.0 2013-02-07      182.0
5017  2330 2013-02-19  106.5 2013-02-19   47438687.0 2013-02-07      182.0
5018  2330 2013-02-20  108.0 2013-02-20   47438687.0 2013-02-07      182.0
5019  2330 2013-02-21  107.0 2013-02-21   47438687.0 2013-02-07      182.0
5020  2330 2013-02-22  105.0 2013-02-22   47438687.0 2013-02-07      182.0
...    ...        ...    ...        ...          ...        ...        ...
7467  2330 2023-02-17  516.0 2023-02-17  200050544.0 2023-02-13      212.0
7468  2330 2023-02-20  511.0 2023-02-20  200050544.0 2023-02-13      212.0
7469  2330 2023-02-21  513.0 2023-02-21  200050544.0 2023-02-13      212.0
7470  2330 2023-02-22  505.0 2023-02-22  200050544.0 2023-02-13      212.0
7471  2330 2023-02-23  510.0 2023-02-23  200050544.0 2023-02-13      212.0

[2456 rows x 7 columns]

In [10]:
stock = tejapi.get('TWN/APIPRCD',
                coid = stks,
                paginate = True,
                opts = {'columns':['coid', 'mdate', 'low_d']})
stock

       coid      mdate  low_d
None
0      1101 1971-01-05  14.20
1      1101 1971-01-06  14.10
2      1101 1971-01-07  14.00
3      1101 1971-01-08  13.90
4      1101 1971-01-09  13.80
...     ...        ...    ...
26513  2882 2023-02-17  43.35
26514  2882 2023-02-20  44.00
26515  2882 2023-02-21  43.55
26516  2882 2023-02-22  43.15
26517  2882 2023-02-23  43.20

[26518 rows x 3 columns]

In [ ]:
stock = tejapi.get('TWN/APIPRCD',
                coid = stks,
                paginate = True,
                opts = {'columns':['coid', 'mdate', 'low_d']})
stock

In [12]:
days = pd.date_range(start='2013-01-01', end='2023-02-24', freq='D')
days = pd.DataFrame({'all_dates':days})

In [13]:
gb = tejapi.get('TWN/APISHRACTW',
                coid = stks,
                paginate = True,
                opts = {'columns':['coid', 'mdate', 'edate1', 'shrm_8_10']})
gb

      coid      mdate     edate1  shrm_8_10
None
0     1101 2013-02-01 2013-02-04         59
1     1101 2013-03-01 2013-03-04         55
2     1101 2013-11-01 2013-11-04         56
3     1101 2014-05-02 2014-05-05         52
4     1101 2014-08-01 2014-08-04         50
...    ...        ...        ...        ...
1183  2882 2022-12-23 2022-12-26        110
1184  2882 2022-12-30 2023-01-02        117
1185  2882 2023-01-13 2023-01-16        118
1186  2882 2023-01-19 2023-01-30        121
1187  2882 2023-02-10 2023-02-13        128

[1188 rows x 4 columns]

In [20]:
all_tables.columns.isin(['coid', 'mdate']).any()

False

In [19]:
all_tables.columns[3:]

Index(['mdate', 'all_dates', 'd0001', 'shrm_8_10'], dtype='object')