In [1]:
import tejapi 
tejapi.ApiConfig.api_base="BASE"
tejapi.ApiConfig.api_key = "YOURKEY"
tejapi.ApiConfig.ignoretz = True
import pandas as pd
import numpy as np
import datetime
import matplotlib.pyplot as plt
from TejToolAPI import *

## 測試API

In [2]:
# random select 5 colunms from the fin_company_group
rand_series = np.random.randint(0, len(para.table_columns), 15)
fin_test_c = para.table_columns.loc[rand_series,'COLUMNS']
test_columns = list(set(fin_test_c))
sorted(test_columns)

['curr',
 'd0025',
 'edate2',
 'fund_ex',
 'idx_mcap',
 'isoi',
 'key3',
 'r106',
 'r402',
 'r405',
 'short_t',
 'shrp_o1000',
 'tmr']

In [3]:
search_table(test_columns)

        COLUMNS         TABLE_NAMES
2          key3        fin_self_acc
6          curr        fin_self_acc
11         isoi        fin_self_acc
18         r106        fin_self_acc
22         r402        fin_self_acc
25         r405        fin_self_acc
28         key3    fin_board_select
32         curr    fin_board_select
37         isoi    fin_board_select
44         r106    fin_board_select
48         r402    fin_board_select
51         r405    fin_board_select
105       d0025         month_sales
122     fund_ex      bargaing_chips
154     short_t      bargaing_chips
169         tmr      bargaing_chips
178      edate2  share_distribution
196  shrp_o1000  share_distribution
216    idx_mcap            stk_attr

In [4]:
stks = ['1101', '2882', '2330','2881']
stks = ['2324']
cols = ['r404']
trigger_tables = triggers(stks, columns=cols, fin_type=['A'])

In [5]:
trigger_tables.keys()

dict_keys(['ticker', 'columns', 'start', 'end', 'transfer_to_chinese', 'fin_type', 'trading_calendar', 'trigger_tables', 'table_name', 'selected_columns', 'api_code', 'api_table', 'fin_self_acc', 'fin_board_select'])

In [6]:
trigger_tables['fin_board_select']

      all_dates  r404_A   no       annd fin_type  coid  sem
0    2013-01-01     NaN  NaN        NaT      NaN   NaN  NaN
1    2013-01-02     NaN  NaN        NaT      NaN   NaN  NaN
2    2013-01-03     NaN  NaN        NaT      NaN   NaN  NaN
3    2013-01-04     NaN  NaN        NaT      NaN   NaN  NaN
4    2013-01-05     NaN  NaN        NaT      NaN   NaN  NaN
...         ...     ...  ...        ...      ...   ...  ...
3713 2023-03-03     0.0  001 2022-03-15        Y  2324    4
3714 2023-03-04     0.0  001 2022-03-15        Y  2324    4
3715 2023-03-05     0.0  001 2022-03-15        Y  2324    4
3716 2023-03-06     0.0  001 2022-03-15        Y  2324    4
3717 2023-03-07     0.0  001 2022-03-15        Y  2324    4

[3718 rows x 7 columns]

In [13]:
stks = ['2324']
# stks = ['1101', '2882', '2330','2881']
cols = ['r404']
all_tables = get_history_data(ticker=stks, columns= cols, transfer_to_chinese=False, fin_type=['A','TTM'])
all_tables

      coid      mdate  r404_A  r404_TTM
0     2324 2013-01-02     NaN       NaN
1     2324 2013-01-03     NaN       NaN
2     2324 2013-01-04     NaN       NaN
3     2324 2013-01-07     NaN       NaN
4     2324 2013-01-08     NaN       NaN
...    ...        ...     ...       ...
2483  2324 2023-02-24  -18.18     -0.81
2484  2324 2023-03-01  -18.18     -0.81
2485  2324 2023-03-02  -18.18     -0.81
2486  2324 2023-03-03  -18.18     -0.81
2487  2324 2023-03-06  -18.18     -0.81

[2488 rows x 4 columns]

In [12]:
all_tables

      coid      mdate  r404_A  r404_TTM
0     1101 2013-01-02     NaN       NaN
1     1101 2013-01-03     NaN       NaN
2     1101 2013-01-04     NaN       NaN
3     1101 2013-01-07     NaN       NaN
4     1101 2013-01-08     NaN       NaN
...    ...        ...     ...       ...
9943  2881 2023-02-24  -63.38    -63.38
9944  2881 2023-03-01  -63.38    -63.38
9945  2881 2023-03-02  -63.38    -63.38
9946  2881 2023-03-03  -63.38    -63.38
9947  2881 2023-03-06  -63.38    -63.38

[9948 rows x 4 columns]

In [2]:
days = pd.date_range(start = para.default_start, end = para.default_end)
days = pd.DataFrame({'all_dates':days})
days

      all_dates
0    2013-01-01
1    2013-01-02
2    2013-01-03
3    2013-01-04
4    2013-01-05
...         ...
3713 2023-03-03
3714 2023-03-04
3715 2023-03-05
3716 2023-03-06
3717 2023-03-07

[3718 rows x 1 columns]

In [3]:
data = tejapi.get('TWN/AFESTM1', coid = '2324', opts={'columns':['mdate','coid', 'key3','r404', 'annd']})
data.tail(15)

          mdate  coid key3   r404       annd
None
141  2021-09-01  2324    A  80.37 2021-11-11
142  2021-09-01  2324    Q  79.69 2021-11-11
143  2021-09-01  2324  TTM  90.29 2021-11-11
144  2021-12-01  2324    A  33.11 2022-03-15
145  2021-12-01  2324    Q -23.39 2022-03-15
146  2021-12-01  2324  TTM  33.11 2022-03-15
147  2022-03-01  2324    A -17.53 2022-05-11
148  2022-03-01  2324    Q -17.53 2022-05-11
149  2022-03-01  2324  TTM   7.14 2022-05-11
150  2022-06-01  2324    A -18.18 2022-08-12
151  2022-06-01  2324    Q -18.86 2022-08-12
152  2022-06-01  2324  TTM  -0.81 2022-08-12
153  2022-12-01  2324    A   0.00 2022-03-15
154  2022-12-01  2324    Q  86.63 2022-03-15
155  2022-12-01  2324  TTM   0.00 2022-03-15

In [ ]:
get(fin_data)

In [23]:
data_sacc_pivot = para.mpf.fin_pivot(data, ['coid','mdate','annd'])
data_sacc_pivot

        mdate  coid  r404_A       annd  r404_Q  r404_TTM
0  2010-03-01  2324  170.77 2010-04-28     NaN     74.92
1  2010-09-01  2324     NaN 2010-10-08     NaN       NaN
2  2010-12-01  2324     NaN 2011-01-10     NaN       NaN
3  2010-12-01  2324   28.47 2011-04-26     NaN     28.47
4  2011-03-01  2324     NaN 2011-04-11     NaN       NaN
5  2011-03-01  2324  -59.37 2011-04-26  -57.86    -19.92
6  2011-06-01  2324     NaN 2011-07-11     NaN       NaN
7  2011-06-01  2324     NaN 2011-08-31     NaN       NaN
8  2011-09-01  2324     NaN 2011-10-11     NaN       NaN
9  2011-09-01  2324  -51.63 2011-11-01     NaN    -46.26
10 2011-12-01  2324     NaN 2012-01-10     NaN       NaN
11 2011-12-01  2324     NaN 2012-03-30     NaN       NaN
12 2012-03-01  2324     NaN 2012-04-10     NaN       NaN
13 2012-03-01  2324     NaN 2012-04-30     NaN       NaN
14 2012-06-01  2324     NaN 2012-08-29     NaN       NaN
15 2012-09-01  2324  -32.69 2012-10-31  -20.29    -41.69
16 2012-12-01  2324     NaN 2013-03-29     NaN       NaN
17 2013-03-01  2324  -38.88 2013-05-09     NaN    -31.96
18 2013-06-01  2324     NaN 2013-08-12     NaN       NaN
19 2013-09-01  2324  -87.02 2013-11-13 -229.00    -68.76
20 2013-12-01  2324     NaN 2014-03-27     NaN       NaN
21 2014-03-01  2324   84.49 2014-05-08   84.50    -29.59
22 2014-06-01  2324     NaN 2014-08-13     NaN       NaN
23 2014-09-01  2324  349.30 2014-11-13  207.30    156.18
24 2014-12-01  2324     NaN 2015-02-26     NaN       NaN
25 2014-12-01  2324  123.31 2015-03-18     NaN    123.31
26 2015-03-01  2324  275.13 2015-05-11  -21.06   1127.62
27 2015-06-01  2324     NaN 2015-08-11     NaN       NaN
28 2015-09-01  2324  102.82 2015-11-12   22.53     83.68
29 2016-03-01  2324  -10.71 2016-05-11  -10.72    -16.38
30 2016-06-01  2324     NaN 2016-08-11     NaN       NaN
31 2016-09-01  2324   -7.60 2016-11-09  -24.74    -21.37
32 2016-12-01  2324    0.18 2017-03-28     NaN      0.18
33 2017-03-01  2324  -36.71 2017-05-10  -36.71     -4.75
34 2017-06-01  2324  -51.19 2017-08-10     NaN    -24.23
35 2017-09-01  2324  -31.48 2017-11-09    4.67    -16.67
36 2017-12-01  2324  -31.31 2018-03-19  -30.94    -31.31
37 2018-03-01  2324     NaN 2018-05-09     NaN       NaN
38 2018-06-01  2324   90.31 2018-08-09  167.82     13.96
39 2018-09-01  2324     NaN 2018-11-08     NaN       NaN
40 2018-12-01  2324   45.30 2019-03-21   -1.01     45.30
41 2019-03-01  2324     NaN 2019-05-13     NaN       NaN
42 2019-06-01  2324   -2.48 2019-08-13  -10.48     12.02
43 2020-09-01  2324   -1.30 2020-11-12     NaN      1.16
44 2020-12-01  2324   31.12 2021-03-26     NaN     31.12
45 2021-03-01  2324  236.99 2021-05-12     NaN     74.73
46 2021-06-01  2324   80.92 2021-08-12     NaN     77.06
47 2021-09-01  2324   80.37 2021-11-11   79.69     90.29
48 2021-12-01  2324   33.11 2022-03-15  -23.39     33.11
49 2022-03-01  2324  -17.53 2022-05-11  -17.53      7.14
50 2022-06-01  2324  -18.18 2022-08-12  -18.86     -0.81
51 2022-12-01  2324    0.00 2022-03-15   86.63      0.00

In [7]:
para.mpf.get_announce_date('2324')

,coid,mdate,fin_od,merg,a_dd,sym8,eym8,term,currency
0,2324,2006-03-01,1,N,2006-04-28,2006-01-01,2006-03-31,3,NTD
1,2324,2006-06-01,1,Y,2006-08-30,2006-04-01,2006-06-30,6,NTD
2,2324,2006-09-01,1,N,2006-10-24,2006-07-01,2006-09-30,9,NTD
3,2324,2006-12-01,1,Y,2007-04-26,2006-10-01,2006-12-31,12,NTD
4,2324,2007-03-01,1,N,2007-04-27,2007-01-01,2007-03-31,3,NTD
...,...,...,...,...,...,...,...,...,...
58,2324,2021-09-01,1,Y,2021-11-15,2021-07-01,2021-09-30,9,NTD
59,2324,2021-12-01,1,Y,2022-03-16,2021-10-01,2021-12-31,12,NTD
60,2324,2022-03-01,1,Y,2022-05-16,2022-01-01,2022-03-31,3,NTD
61,2324,2022-06-01,1,Y,2022-08-15,2022-04-01,2022-06-30,6,NTD
62,2324,2022-09-01,1,Y,2022-11-14,2022-07-01,2022-09-30,9,NTD

In [30]:
data_sacc = days.merge(data_sacc_pivot, how = 'left', left_on = 'all_dates', right_on = 'annd').ffill()
data_sacc

      all_dates      mdate  coid  r404_A       annd  r404_Q  r404_TTM
0    2013-01-01        NaT   NaN     NaN        NaT     NaN       NaN
1    2013-01-02        NaT   NaN     NaN        NaT     NaN       NaN
2    2013-01-03        NaT   NaN     NaN        NaT     NaN       NaN
3    2013-01-04        NaT   NaN     NaN        NaT     NaN       NaN
4    2013-01-05        NaT   NaN     NaN        NaT     NaN       NaN
...         ...        ...   ...     ...        ...     ...       ...
3714 2023-03-03 2022-06-01  2324  -18.18 2022-08-12  -18.86     -0.81
3715 2023-03-04 2022-06-01  2324  -18.18 2022-08-12  -18.86     -0.81
3716 2023-03-05 2022-06-01  2324  -18.18 2022-08-12  -18.86     -0.81
3717 2023-03-06 2022-06-01  2324  -18.18 2022-08-12  -18.86     -0.81
3718 2023-03-07 2022-06-01  2324  -18.18 2022-08-12  -18.86     -0.81

[3719 rows x 7 columns]

In [22]:
data_board = tejapi.get('TWN/AFESTMD', coid = '2324', opts={'columns':['mdate','coid', 'key3','r404', 'annd']})
data_board

          mdate  coid key3   r404       annd
None
0    2022-12-01  2324    A   0.00 2022-03-15
1    2022-12-01  2324    Q  86.63 2022-03-15
2    2022-12-01  2324  TTM   0.00 2022-03-15

In [24]:
data_board_pivot = para.mpf.fin_pivot(data_board, ['coid','mdate','annd'])
data_board_pivot

       mdate  coid  r404_A       annd  r404_Q  r404_TTM
0 2022-12-01  2324     0.0 2022-03-15   86.63       0.0

## 財簽資料測試

In [22]:
fin_auditor = tejapi.get('TWN/AINVFINQ', coid = '1101', opts = {'pivot':True})
fin_auditor

,coid,mdate,fin_od,BP11,BP12,BP21,BP22,BP31,BP41,BP51,...,M304,R305,M305,R306,M306,R316,M316,M317,R834,M834
None,,,,,,,,,,,,,,,,,,,,,
0,1101,2005-03-01,1,1546033.0,0.0,3907552.0,0.0,1176162.0,788680.0,43774509.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5241.81802,NaN
1,1101,2005-06-01,1,10711519.0,0.0,7731824.0,0.0,4700958.0,1887465.0,102738996.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6525.52984,NaN
2,1101,2005-09-01,1,6250793.0,0.0,4097682.0,0.0,1032275.0,1192190.0,42467000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-10723.87556,NaN
3,1101,2005-12-01,1,10873922.0,0.0,7305856.0,0.0,3969019.0,2669571.0,103112732.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13178.49774,NaN
4,1101,2006-03-01,1,5172940.0,0.0,4149855.0,0.0,1468836.0,1352767.0,41583135.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5676.29260,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99,1101,2021-09-01,2,59958809.0,0.0,36493940.0,24928581.0,11238700.0,8274800.0,114975260.0,...,17.37080,0.62964,3.82861,0.76610,4.63193,0.69183,3.84134,3.19310,2475.72592,9797.59403
100,1101,2021-12-01,1,91121942.0,0.0,35940929.0,24334423.0,13412511.0,10023071.0,120950826.0,...,17.47549,0.76390,3.23032,1.09915,4.25748,0.80996,3.46130,2.87099,2525.91199,8971.70832
101,1101,2022-03-01,1,98040416.0,0.0,33801330.0,24108219.0,13552203.0,11279929.0,127245067.0,...,17.62827,0.03390,2.57729,0.19136,3.65621,0.13983,2.99213,2.49143,1925.52686,9050.14341
102,1101,2022-06-01,1,100497555.0,0.0,29399946.0,23198379.0,18318975.0,13304491.0,130731263.0,...,17.16986,-0.32777,1.09956,-0.07098,1.98550,-0.15358,1.48792,1.31791,2110.28690,8814.80027
103,1101,2022-09-01,1,95367543.0,0.0,33218170.0,22101820.0,17682787.0,13906734.0,137067245.0,...,16.24229,0.09316,0.52055,0.31224,1.42116,0.24325,0.96725,0.83028,2608.58570,9170.31146

In [44]:
fin_columns = pd.read_excel('./不用的/TQ_Analytics+資料欄位查詢.xlsx', sheet_name='財務資訊_財報')
fin_columns

     會計科目   欄位中文名稱                         欄位英文名稱
0    BP11  現金及約當現金       Cash_and_Cash_equivalent
1    BP12     存放同業        Deposit_interbank_funds
2    BP21     應收帳款            Accounts_Receivable
3    BP22    長期應收款  Long_term_Accounts_Receivable
4    BP31       存貨                    Inventories
..    ...      ...                            ...
164  R304   每股營業收入                Sales_Per_Share
165  R305   每股營業利益     Operating_Income_Per_Share
166  R306   每股稅前淨益       Pre_Tax_Income_Per_Share
167  R316   每股稅後淨利           Net_Income_Per_Share
168  R834     每人營收             Sales_Per_Employee

[169 rows x 3 columns]

In [46]:
lost = []
for i in fin_auditor.columns:
    if i not in fin_columns['會計科目']:
        lost.append(i)
lost

['coid',
 'mdate',
 'fin_od',
 'BP11',
 'BP12',
 'BP21',
 'BP22',
 'BP31',
 'BP41',
 'BP51',
 'BP52',
 'BP53',
 'BP54',
 'BP61',
 'BP62',
 'BP63',
 'BP64',
 'BP71',
 'BP72',
 'BP96',
 'BP97',
 'BP98',
 'BP99',
 'BV11',
 'BV12',
 'BV13',
 'BV14',
 'BV21',
 'BV31',
 'BV41',
 'BV42',
 'BF11',
 'BF12',
 'BF21',
 'BF22',
 'BF31',
 'BF41',
 'BF42',
 'BF43',
 'BF44',
 'BF45',
 'BF99',
 'BSCA',
 'BSNCA',
 'BSTA',
 'BSCL',
 'BSNCL',
 'BSTL',
 'BSSE',
 'BSLSE',
 'DEBT',
 'MCSH',
 'QUICK2',
 'QUICK',
 'PPE',
 'AR',
 'IP11',
 'IP12',
 'IP13',
 'IP21',
 'IP22',
 'IP23',
 'IP31',
 'IP41',
 'IP42',
 'IP43',
 'IP44',
 'IP45',
 'IP51',
 'IP99',
 'IP98',
 'IP97',
 'IV11',
 'IV21',
 'IV22',
 'IV23',
 'IV24',
 'IV31',
 'IV32',
 'IV33',
 'IV41',
 'IF11',
 'IF21',
 'IF31',
 'ISOI',
 'ISIBT',
 'ISNI',
 'ISNIP',
 'EPS',
 'ISPSD',
 'GM',
 'OPI',
 'NRI',
 'RI',
 'NOPI',
 'EBIT',
 'CP11',
 'CP21',
 'CP31',
 'CP32',
 'CISNI',
 'CIP21',
 'CIP22',
 'CIP31',
 'CIP41',
 'CIP42',
 'CBP21',
 'CBP31',
 'CBP41',
 'CBP61',
 'CBP62',
 'CBP63',
 'CBP64',
 'CP51',
 'CV11',
 'CV12',
 'CV21',
 'CV22',
 'CV31',
 'CV32',
 'CV41',
 'CF11',
 'CF12',
 'CF21',
 'CF31',
 'CF41',
 'CT11',
 'CT21',
 'CSCHG',
 'CSBCH',
 'CSCFO',
 'CSCFI',
 'CSCFF',
 'CSECH',
 'VCIP31',
 'XP11',
 'XP12',
 'XP13',
 'XP14',
 'XV11',
 'XV12',
 'XF11',
 'XF21',
 'XSEXI',
 'PERSON',
 'SHARES',
 'WAVG',
 'TAXRATE',
 'R104',
 'M104',
 'R115',
 'M115',
 'R105',
 'M105',
 'R106',
 'M106',
 'R107',
 'M107',
 'R108',
 'M108',
 'R201',
 'M201',
 'R112',
 'M112',
 'R401',
 'R402',
 'R403',
 'R404',
 'R405',
 'R408',
 'R409',
 'R410',
 'R502',
 'R501',
 'R205',
 'M205',
 'R505',
 'R517',
 'M517',
 'R512',
 'M512',
 'R509',
 'R608',
 'M608',
 'R616',
 'M616',
 'R610',
 'M610',
 'R607',
 'M607',
 'R613',
 'M613',
 'R612',
 'M612',
 'R609',
 'M609',
 'R614',
 'M614',
 'R611',
 'M611',
 'R615',
 'M615',
 'R307',
 'R304',
 'M304',
 'R305',
 'M305',
 'R306',
 'M306',
 'R316',
 'M316',
 'M317',
 'R834',
 'M834']

In [15]:
data = tejapi.get('TWN/AINVFINQA',
                    coid = '1101',
                    paginate = True,
                    chinese_column_name=False)
data

,coid,mdate,fin_od,merg,a_dd,sym8,eym8,term,currency
None,,,,,,,,,
0,1101,2005-03-01,1,N,2006-04-30,2005-01-01,2005-03-31,3,NTD
1,1101,2005-06-01,1,Y,2006-08-31,2005-04-01,2005-06-30,6,NTD
2,1101,2005-09-01,1,N,2006-10-31,2005-07-01,2005-09-30,9,NTD
3,1101,2005-12-01,1,Y,2007-04-24,2005-10-01,2005-12-31,12,NTD
4,1101,2006-03-01,1,N,2006-04-30,2006-01-01,2006-03-31,3,NTD
...,...,...,...,...,...,...,...,...,...
99,1101,2021-09-01,2,Y,2022-11-10,2021-07-01,2021-09-30,9,NTD
100,1101,2021-12-01,1,Y,2022-02-25,2021-10-01,2021-12-31,12,NTD
101,1101,2022-03-01,1,Y,2022-05-10,2022-01-01,2022-03-31,3,NTD
102,1101,2022-06-01,1,Y,2022-08-12,2022-04-01,2022-06-30,6,NTD
103,1101,2022-09-01,1,Y,2022-11-10,2022-07-01,2022-09-30,9,NTD

In [10]:
fin_date = para.mpf.get_announce_date('1101')
fin_date

,coid,mdate,fin_od,merg,a_dd,sym8,eym8,term,currency
0,1101,2006-03-01,1,N,2006-04-30,2006-01-01,2006-03-31,3,NTD
1,1101,2006-06-01,1,Y,2006-08-31,2006-04-01,2006-06-30,6,NTD
2,1101,2006-09-01,1,N,2006-10-31,2006-07-01,2006-09-30,9,NTD
3,1101,2006-12-01,1,Y,2007-04-24,2006-10-01,2006-12-31,12,NTD
4,1101,2007-03-01,1,N,2007-04-30,2007-01-01,2007-03-31,3,NTD
...,...,...,...,...,...,...,...,...,...
57,1101,2021-09-01,1,Y,2021-11-11,2021-07-01,2021-09-30,9,NTD
58,1101,2021-12-01,1,Y,2022-02-25,2021-10-01,2021-12-31,12,NTD
59,1101,2022-03-01,1,Y,2022-05-10,2022-01-01,2022-03-31,3,NTD
60,1101,2022-06-01,1,Y,2022-08-12,2022-04-01,2022-06-30,6,NTD
61,1101,2022-09-01,1,Y,2022-11-10,2022-07-01,2022-09-30,9,NTD

In [58]:
fin_auditor[['coid', 'mdate', 'fin_od']]

      coid      mdate  fin_od
None
0     1101 2005-03-01       1
1     1101 2005-06-01       1
2     1101 2005-09-01       1
3     1101 2005-12-01       1
4     1101 2006-03-01       1
...    ...        ...     ...
99    1101 2021-09-01       2
100   1101 2021-12-01       1
101   1101 2022-03-01       1
102   1101 2022-06-01       1
103   1101 2022-09-01       1

[104 rows x 3 columns]

In [67]:
temp = fin_date.merge(fin_auditor, how = 'left', on = ['coid', 'mdate', 'fin_od'])
temp

,coid,mdate,fin_od,merg,a_dd,sym8,eym8,term,currency,BP11,...,M304,R305,M305,R306,M306,R316,M316,M317,R834,M834
0,1101,2006-03-01,1,N,2006-04-30,2006-01-01,2006-03-31,3,NTD,5172940.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5676.29260,NaN
1,1101,2006-06-01,1,Y,2006-08-31,2006-04-01,2006-06-30,6,NTD,15066623.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6763.19439,NaN
2,1101,2006-09-01,1,N,2006-10-31,2006-07-01,2006-09-30,9,NTD,2714230.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-8132.83480,NaN
3,1101,2006-12-01,1,Y,2007-04-24,2006-10-01,2006-12-31,12,NTD,8115728.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12494.91274,17875.65511
4,1101,2007-03-01,1,N,2007-04-30,2007-01-01,2007-03-31,3,NTD,3999811.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4639.29675,46934.69819
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,1101,2021-09-01,1,Y,2021-11-11,2021-07-01,2021-09-30,9,NTD,59958809.0,...,18.75156,0.62964,3.78038,0.76610,4.55587,0.69183,3.84134,3.20702,2475.72592,10576.37686
58,1101,2021-12-01,1,Y,2022-02-25,2021-10-01,2021-12-31,12,NTD,91121942.0,...,17.47549,0.76390,3.23032,1.09915,4.25748,0.80996,3.46130,2.87099,2525.91199,8971.70832
59,1101,2022-03-01,1,Y,2022-05-10,2022-01-01,2022-03-31,3,NTD,98040416.0,...,17.62827,0.03390,2.57729,0.19136,3.65621,0.13983,2.99213,2.49143,1925.52686,9050.14341
60,1101,2022-06-01,1,Y,2022-08-12,2022-04-01,2022-06-30,6,NTD,100497555.0,...,17.16986,-0.32777,1.09956,-0.07098,1.98550,-0.15358,1.48792,1.31791,2110.28690,8814.80027
61,1101,2022-09-01,1,Y,2022-11-10,2022-07-01,2022-09-30,9,NTD,95367543.0,...,16.24229,0.09316,0.52055,0.31224,1.42116,0.24325,0.96725,0.83028,2608.58570,9170.31146

In [68]:
data_final = days.merge(temp, how = 'left', left_on = 'all_dates', right_on = 'a_dd').ffill()
data_final

,all_dates,coid,mdate,fin_od,merg,a_dd,sym8,eym8,term,currency,...,M304,R305,M305,R306,M306,R316,M316,M317,R834,M834
0,2013-01-01,NaN,NaT,NaN,NaN,NaT,NaT,NaT,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2013-01-02,NaN,NaT,NaN,NaN,NaT,NaT,NaT,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2013-01-03,NaN,NaT,NaN,NaN,NaT,NaT,NaT,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2013-01-04,NaN,NaT,NaN,NaN,NaT,NaT,NaT,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2013-01-05,NaN,NaT,NaN,NaN,NaT,NaT,NaT,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3713,2023-03-03,1101,2022-09-01,1.0,Y,2022-11-10,2022-07-01,2022-09-30,9.0,NTD,...,16.24229,0.09316,0.52055,0.31224,1.42116,0.24325,0.96725,0.83028,2608.5857,9170.31146
3714,2023-03-04,1101,2022-09-01,1.0,Y,2022-11-10,2022-07-01,2022-09-30,9.0,NTD,...,16.24229,0.09316,0.52055,0.31224,1.42116,0.24325,0.96725,0.83028,2608.5857,9170.31146
3715,2023-03-05,1101,2022-09-01,1.0,Y,2022-11-10,2022-07-01,2022-09-30,9.0,NTD,...,16.24229,0.09316,0.52055,0.31224,1.42116,0.24325,0.96725,0.83028,2608.5857,9170.31146
3716,2023-03-06,1101,2022-09-01,1.0,Y,2022-11-10,2022-07-01,2022-09-30,9.0,NTD,...,16.24229,0.09316,0.52055,0.31224,1.42116,0.24325,0.96725,0.83028,2608.5857,9170.31146
3717,2023-03-07,1101,2022-09-01,1.0,Y,2022-11-10,2022-07-01,2022-09-30,9.0,NTD,...,16.24229,0.09316,0.52055,0.31224,1.42116,0.24325,0.96725,0.83028,2608.5857,9170.31146

In [64]:
data_final.query('merg == ')

Empty DataFrame
Columns: [all_dates, coid, mdate, fin_od, merg, a_dd, sym8, eym8, term, currency, BP11, BP12, BP21, BP22, BP31, BP41, BP51, BP52, BP53, BP54, BP61, BP62, BP63, BP64, BP71, BP72, BP96, BP97, BP98, BP99, BV11, BV12, BV13, BV14, BV21, BV31, BV41, BV42, BF11, BF12, BF21, BF22, BF31, BF41, BF42, BF43, BF44, BF45, BF99, BSCA, BSNCA, BSTA, BSCL, BSNCL, BSTL, BSSE, BSLSE, DEBT, MCSH, QUICK2, QUICK, PPE, AR, IP11, IP12, IP13, IP21, IP22, IP23, IP31, IP41, IP42, IP43, IP44, IP45, IP51, IP99, IP98, IP97, IV11, IV21, IV22, IV23, IV24, IV31, IV32, IV33, IV41, IF11, IF21, IF31, ISOI, ISIBT, ISNI, ISNIP, EPS, ISPSD, GM, OPI, NRI, ...]
Index: []

[0 rows x 221 columns]